type: "HandLandmarkTrackingCpu"
input_stream: "IMAGE:image"
output_stream: "LANDMARKS:multi_hand_landmarks"
output_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"
output_stream: "HANDEDNESS:multi_handedness"
output_stream: "PALM_DETECTIONS:palm_detections"
output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"

# Determines if the number of hands detected for the previous frame is equal to (or larger than)
# the pipeline defined num_hands which it expects to track.
node {
  calculator: "HeadCalculator"

  input_stream: "IMAGE:image"
  input_stream: "ITERABLE:prev_hand_rects_from_landmarks"

# output_stream: "TENSORS:detection_input_tensor"
# output_stream: "LETTERBOX_PADDING:detection_letterbox_padding"
# output_stream: "DETECTIONS:palm_detections"
# output_stream: "ITERABLE:hand_rects_from_palm_detections"

  output_stream: "prev_has_enough_hands"
  output_stream: "hand_rects"
}

# Drops the incoming image from reaching palm detection, if enough hands have already been identified
# for the previous image. Otherwise, passes the incoming image through to trigger a new round of
# palm detection. left around till final stage of liberation ― to keep all calculators' Process
# method being called till the final switch.
#node {
#  calculator: "GateCalculator"
#  input_stream: "image"
#  input_stream: "DISALLOW:prev_has_enough_hands"
#  output_stream: "palm_detection_image"
#  options: {
#    [mediapipe_v01013_based.GateCalculatorOptions.ext] {
#      empty_packets_as_allow: true
#    }
#  }
#}

### beginning of the original palm detection subgraph's nodes ###

# Transforms an image into a 128x128 tensor while keeping the aspect ratio, and
# therefore will result in letterboxing unless the input image was somehow rectangular,
# which an image taken from a webcam in our scenario is not.
#node {
#  calculator: "ImageToTensorCalculator"
#  input_stream: "IMAGE:palm_detection_image"
#  output_stream: "TENSORS:detection_input_tensor"
#  output_stream: "LETTERBOX_PADDING:detection_letterbox_padding"
#}

# Runs the TensorFlow Lite SSD palm detection model
#node {
#  calculator: "DetectionInferenceCalculator"
#  input_stream: "TENSORS:detection_input_tensor"
#  output_stream: "TENSORS:detection_tensors"
#  options: {
#    [mediapipe_v01013_based.InferenceCalculatorOptions.ext] {
#      delegate { xnnpack {} }
#    }
#  }
#}
#
## Decodes the detection tensors generated by the SSD palms detection model into
## mediapipe Detection objects, while filtering the network's outputs by several
## criteria including finally applying Non-Maximum Suppression (NMS).
#node {
#  calculator: "ConvertDetectionTensorsCalculator"
#  input_stream: "TENSORS:detection_tensors"
#  output_stream: "DETECTIONS:filtered_detections"
#}
#
## translates the detection coordinates to the original image coordinates,
## thus undoing the effect of the letterboxing which was necessary for using the neural network model:
##  Adjusts detection locations (already normalized to [0.f, 1.f]) on the letterboxed image (after image
## transformation with the FIT scale mode) to the corresponding locations on the same image with the letterbox
## removed (the input image to the graph before image transformation).
#node {
#  calculator: "UnletterboxCalculator"
#  input_stream: "DETECTIONS:filtered_detections"
#  input_stream: "LETTERBOX_PADDING:detection_letterbox_padding"
#  output_stream: "DETECTIONS:detections"
#}
#
## Makes sure there are no more detections than the provided num_hands.
#node {
#  calculator: "FilterDetectionsToMaxNumHands"
#  input_stream: "detections"
#  output_stream: "palm_detections"
#}

### end of the original palm detection subgraph's nodes ###

# Extracts image size.
node {
  calculator: "ImageSize"
  input_stream: "IMAGE:image"
  output_stream: "SIZE:image_size"
}

# loop inducer node:
# Outputs each element of palm_detections at a fake timestamp for the rest of
# the graph to process. Clones the image size packet for each palm_detection at
# the fake timestamp. At the end of the loop, outputs the BATCH_END timestamp
# for downstream calculators to inform them that all elements in the vector have
# been processed.
#node {
#  calculator: "DetectionsFanOut"
#  input_stream: "ITERABLE:palm_detections"
#  input_stream: "CLONE:image_size"
#  output_stream: "ITEM:palm_detection"
#  output_stream: "CLONE:image_size_for_palms"
#  output_stream: "BATCH_END:palm_detections_timestamp"
#}

# Converts results of a single palm detection into a rectangle (normalized by image size)
# that encloses the palm and is rotated such that the line connecting center of
# the wrist and MCP of the middle finger is aligned with the Y-axis of the
# rectangle.
#node {
#  calculator: "PalmDetectionToHandRectStage1"
#  input_stream: "DETECTION:palm_detection"
#  input_stream: "IMAGE_SIZE:image_size_for_palms"
#  output_stream: "NORM_RECT:raw_roi"
#}

# Expands and shifts the rectangle that contains the palm so that it's likely to cover the entire hand.
#node {
#  calculator: "PalmDetectionToHandRectStage2"
#  input_stream: "NORM_RECT:raw_roi"
#  input_stream: "IMAGE_SIZE:image_size_for_palms"
#  output_stream: "hand_rect_from_palm_detection"
#  options: {
#    [mediapipe_v01013_based.RectTransformationCalculatorOptions.ext] {
#      scale_x: 2.6
#      scale_y: 2.6
#      shift_y: -0.5
#      square_long: true
#    }
#  }
#}

# collects the final set of hand detection rectangles, into a vector of them.
# outputs that vector upon receiving the BATCH_END timestamp.
#node {
#  calculator: "DetectionHandRectsCollector"
#  input_stream: "ITEM:hand_rect_from_palm_detection"
#  input_stream: "BATCH_END:palm_detections_timestamp"
#  output_stream: "ITERABLE:hand_rects_from_palm_detections"
#}

#
# smashes together palm detections from the current frame's explicit palm detection inference
# and those derived from the previous frame's landmarks inference, filtering out any partially overlapping ones
# (by its overlap threshold) by a greedy ordering where the last wins. in our case, the last stream is
# (not-intuitively) that of the *previous frame's landmarks-derived palm detections*.
#
# differetly put it filters down partially overlapping hand rects by its own overlap threshold criterion,
# from both of its input streams, thus yielding a single output set of palm detections where no two overlap
# beyond the said threshold.
#
# so in those cases where palm detection was triggered AND we have previous landmarks-derived palm detections,
# i.e. we didn't reach the pipeline's constant expected number of hands in the landmarks inference of the previous frame ―
# which is very probably when there's distinctively enough only one hand in the frame but two are the number aiming for ―
# the current frame's processing will throw away the palms detected explicitly by it most of the time ...
# if they overlap partially enough with the previous frame's landmarks-derived palm detections.
#
# on the other hand, if the number of hands expected is set to one, there won't usually even be two streams
# to smash together, only one, as the palm detection won't even kick into action most of the time.
#
# as the current node only filters by overlap, its prioritization of survival between the streams
# is not even helpful for sticking with an already tracked hand when a second hand comes into view.
#
# a weak baseline for robustness to hand ids across frames may emerge from the constant order of the SSD detection bounding boxes ...
# not from the current node, which is not associating anything, as it doesn't even try to. its original impl. had logic for
# associating hand ID's but the current pipeline never provided it with ID's for hands to begin with, not even in the base
# v0.10.13 code level which our baseline branch represents.
#
#node {
#  calculator: "HandRectsAssociation"
#  input_stream: "hand_rects_from_palm_detections"
#  input_stream: "prev_hand_rects_from_landmarks"
#  output_stream: "hand_rects"
#  options: {
#    [mediapipe_v01013_based.AssociationCalculatorOptions.ext] {
#      min_similarity_threshold: 0.5
#    }
#  }
#}

# loop inducer node:
# Outputs each element of hand_rects for the rest of the graph to process.
# Clones image and image size packets for each single_hand_rect at a synthetic timestamp per each hand_rect.
# At the end of the loop, outputs the BATCH_END timestamp for downstream calculators to inform them that all
# elements in the vector have been processed.
node {
  calculator: "HandRectsFanOut"
  input_stream: "ITERABLE:hand_rects"
  input_stream: "CLONE:0:image"
  input_stream: "CLONE:1:image_size"
  output_stream: "ITEM:single_hand_rect"
  output_stream: "CLONE:0:image_for_landmarks"
  output_stream: "CLONE:1:image_size_for_landmarks"
  output_stream: "BATCH_END:hand_rects_timestamp"
}

### beginning of the original hand landmark inference subgraph's nodes ###

# Transforms a region of image into a 224x224 tensor while keeping the aspect
# ratio, and therefore may result in potential letterboxing.
node {
  calculator: "ExtractSubImageForInference"
  input_stream: "IMAGE:image_for_landmarks"
  input_stream: "NORM_RECT:single_hand_rect"
  output_stream: "TENSORS:input_tensor"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
}

# Runs a TensorFlow Lite model on CPU that takes an image tensor and outputs a
# vector of tensors representing, for instance, detection boxes/keypoints and
# scores.
node {
  calculator: "LandmarksInferenceCalculator"
  input_stream: "TENSORS:input_tensor"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe_v01013_based.InferenceCalculatorOptions.ext] {
      delegate {
        xnnpack {}
      }
    }
  }
}

# Splits the landmark's inference output vector of tensors by topic:
# • landmark_tensors: the inferred viewport hand landmark coordinates
# • hand_flag_tensor: weather a hand was deemed actually there in the input rectnagle or not (a confidence score)
# • handedness_tensor: the handedness classification scores (left vs right hand confidence)
# • world_landmark_tensor: the inferred object hand landmark coordinates
node {
  calculator: "SplitInferenceOutputTopics"
  input_stream: "output_tensors"
  output_stream: "landmark_tensors"
  output_stream: "hand_flag_tensor"
  output_stream: "handedness_tensor"
  output_stream: "world_landmark_tensor"
  options: {
    [mediapipe_v01013_based.SplitVectorCalculatorOptions.ext] {
      ranges: { begin: 0 end: 1 }
      ranges: { begin: 1 end: 2 }
      ranges: { begin: 2 end: 3 }
      ranges: { begin: 3 end: 4 }
    }
  }
}

# Converts the hand-flag tensor into a float that represents the confidence score of hand presence.
node {
  calculator: "ExtractHandPresence"
  input_stream: "TENSORS:hand_flag_tensor"
  output_stream: "FLOAT:hand_presence_score"
}

# Thresholds the hand presence confidence score.
# Presumbaly, when the threshold isn't met, the hand will be ignored,
# and also not pass back a hand rectangle for the next frame's processing.
node {
  calculator: "HandPresenceGating"
  input_stream: "FLOAT:hand_presence_score"
  output_stream: "FLAG:hand_presence"
  options: {
    [mediapipe_v01013_based.ThresholdingCalculatorOptions.ext] {
      threshold: 0.5
    }
  }
}

# Drops the handedness tensor if hand is not present.
node {
  calculator: "GateCalculator"
  input_stream: "handedness_tensor"
  input_stream: "ALLOW:hand_presence"
  output_stream: "ensured_handedness_tensor"
}

# Converts the handedness tensor into a float that represents the classification score of handedness.
node {
  calculator: "ExtractHandednessClassification"
  input_stream: "TENSORS:ensured_handedness_tensor"
  output_stream: "CLASSIFICATIONS:single_handedness"
  options: {
    [mediapipe_v01013_based.TensorsToClassificationCalculatorOptions.ext] {
      top_k: 1
      label_map_path: "mediapipe/modules/hand_landmark/handedness.txt"
      binary_classification: true
    }
  }
}

# Drops the landmarks tensors if hand is not present.
node {
  calculator: "GateCalculator"
  input_stream: "landmark_tensors"
  input_stream: "ALLOW:hand_presence"
  output_stream: "ensured_landmark_tensors"
}

# converts the inferred landmark tensors to mediapipe objects,
# and normalizes them to the size of the input image given to the model.
# this isn't a very great example of software engineering cohesion.
node {
  calculator: "ExtractLandmarks"
  input_stream: "TENSORS:ensured_landmark_tensors"
  output_stream: "NORM_LANDMARKS:landmarks"
  options: {
    [mediapipe_v01013_based.TensorsToLandmarksCalculatorOptions.ext] {
      num_landmarks: 21
      input_image_width: 224
      input_image_height: 224
      # The additional scaling factor is used to account for the Z coordinate
      # distribution in the training data.
      normalize_z: 0.4
    }
  }
}

# adjusts the landmark coordinates (already normalized to [0.f, 1.f]) of the letterboxed hand image used
# by the inference step to the corresponding locations on the same image with the letterbox removed
# (i.e. to the hand image as it were before the letterboxing).
node {
  calculator: "UnletterboxLandmarksPrediction"
  input_stream: "LANDMARKS:landmarks"
  input_stream: "LETTERBOX_PADDING:letterbox_padding"
  output_stream: "LANDMARKS:scaled_landmarks"
}

# last stage on adapting the landmark coordinates to the image coordinates ― this completes the work of
# the last two steps. this step just places, stretches, rotates the output landmarks from their rectangle
# passed to inference, to their viewport interpretation which is a totally naive and no-surprises transformation;
# it just does what you'd think needs be done to place the inference of the passed rectangle in the original
# image's coordinate system. there's no sophisticated real projection that's happening here, it's all just
# fitting the coordinates back to the original image's coordinate system.
node {
  calculator: "LandmarkProjectionCalculator"
  input_stream: "NORM_LANDMARKS:scaled_landmarks"
  input_stream: "NORM_RECT:single_hand_rect"
  output_stream: "NORM_LANDMARKS:single_hand_landmarks"
}

# Drops the world landmarks tensors if hand is not present.
node {
  calculator: "GateCalculator"
  input_stream: "world_landmark_tensor"
  input_stream: "ALLOW:hand_presence"
  output_stream: "ensured_world_landmark_tensor"
}

# merely converts the tensors into the mediapipe landmark object type.
node {
  calculator: "ExtractWorldLandmarks"
  input_stream: "TENSORS:ensured_world_landmark_tensor"
  output_stream: "LANDMARKS:unprojected_world_landmarks"
  options: {
    [mediapipe_v01013_based.TensorsToLandmarksCalculatorOptions.ext] {
      num_landmarks: 21
    }
  }
}

# merely un-rotates the object landmarks by the exact rotation which was passed to the inference step,
# which is the only geometric transformation needed after the inference step for object landmarks.
# there's no sophisticated real projection that's happening here.
node {
  calculator: "WorldLandmarkProjectionCalculator"
  input_stream: "LANDMARKS:unprojected_world_landmarks"
  input_stream: "NORM_RECT:single_hand_rect"
  output_stream: "LANDMARKS:single_hand_world_landmarks"
}

### end of the original hand landmark inference nodes ###

# collects the handedness for each single hand, into a vector of them.
# Upon receiving the BATCH_END timestamp, outputs a vector of them
node {
  calculator: "CollectHandednessClassifications"
  input_stream: "ITEM:single_handedness"
  input_stream: "BATCH_END:hand_rects_timestamp"
  output_stream: "ITERABLE:multi_handedness"
}

# makes a bounding box for the hand based on its landmarks, based on an anatomically-inspired heuristic.
# so this bounding box which is heuristically computed by hand anatomy assumptions, is expected to more tightly
# wrap the hand than the one which was given to the landmark inference step to begin with.
node {
  calculator: "HandRectFromLandmarksStage"
  input_stream: "NORM_LANDMARKS:single_hand_landmarks"
  input_stream: "IMAGE_SIZE:image_size_for_landmarks"
  output_stream: "NORM_RECT:hand_rect_from_landmarks"
}

# expands that hand rectangle so that it's likely to still contain the hand
# after whatever motion of the hand in the next video frame.
node {
  calculator: "DeriveAnticipatoryHandRect"
  input_stream: "NORM_RECT:hand_rect_from_landmarks"
  input_stream: "IMAGE_SIZE:image_size_for_landmarks"
  output_stream: "single_hand_rect_from_landmarks"
  options: {
    [mediapipe_v01013_based.RectTransformationCalculatorOptions.ext] {
      scale_x: 2.0
      scale_y: 2.0
      shift_y: -0.1
      square_long: true
    }
  }
}

# collects the set of landmarks of each hand, into a vector of them.
# outputs that vector upon receiving the BATCH_END timestamp.
node {
  calculator: "CollectFinalLandmarksOfHands"
  input_stream: "ITEM:single_hand_landmarks"
  input_stream: "BATCH_END:hand_rects_timestamp"
  output_stream: "ITERABLE:multi_hand_landmarks"
}

# collects a set of world landmarks of each hand, into a vector of them.
# outputs that vector upon receiving the BATCH_END timestamp.
node {
  calculator: "CollectFinalWorldLandmarksOfHands"
  input_stream: "ITEM:single_hand_world_landmarks"
  input_stream: "BATCH_END:hand_rects_timestamp"
  output_stream: "ITERABLE:multi_hand_world_landmarks"
}

# collects the set of hand rects calculated from the inferred landmarks, into a vector of them.
# outputs that vector upon receiving the BATCH_END timestamp.
node {
  calculator: "CollectAnticipatoryHandRects"
  input_stream: "ITEM:single_hand_rect_from_landmarks"
  input_stream: "BATCH_END:hand_rects_timestamp"
  output_stream: "ITERABLE:hand_rects_from_landmarks"
}

# Caches hand rects calculated from landmarks, and upon the arrival of the next
# input image, sends out the cached rects with timestamps replaced by that of
# the input image, essentially generating a packet that carries the previous
# hand rects. Note that upon the arrival of the very first input image, a
# timestamp bound update occurs to jump start the feedback loop.
node {
  calculator: "LoopbackAnticipatoryHandRects"
  input_stream: "MAIN:image"
  input_stream: "LOOP:hand_rects_from_landmarks"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:prev_hand_rects_from_landmarks"
}
