type: "HandLandmarkTrackingCpu"
input_stream: "IMAGE:image"
output_stream: "LANDMARKS:multi_hand_landmarks"
output_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"
output_stream: "HANDEDNESS:multi_handedness"
#output_stream: "PALM_DETECTIONS:palm_detections"
#output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
#output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"

node {
  calculator: "HandTrackingCalculator"
  input_stream: "IMAGE:image"
  output_stream: "LANDMARKS:multi_hand_landmarks"
  output_stream: "WORLD_LANDMARKS:multi_hand_world_landmarks"
  output_stream: "HANDEDNESS:multi_handedness"
# output_stream: "TENSORS:detection_input_tensor"
# output_stream: "LETTERBOX_PADDING:detection_letterbox_padding"
# output_stream: "DETECTIONS:palm_detections"
# output_stream: "ITERABLE:hand_rects_from_palm_detections"
# output_stream: "prev_has_enough_hands"
#  output_stream: "hand_rects"
}
