"""Copyright 2019 The MediaPipe Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

# Explicitly import and expose the pipeline_output_pb2 module, which is generated from the corresponding .proto file.
# (The IDE doesn't know this symbol since it's python code is only generated by `pip install .` into the target venv).
# unlike other classes built from protobuf definitions, this one is only required for our own pipeline output data type,
# and not for the mediapipe library itself, hence we put it separately here.
from mediapipe.examples.desktop.pipeline_output_pb2 import *
