#include "mediapipe/examples/desktop/hands_pipeline_operator_c_api.h"
#include "mediapipe/examples/desktop/hands_pipeline_operator.h"
#include <string>
#include <vector>
#include <sstream>
#include <mutex>
#include <memory>
#include <cstring>
#include <opencv2/core.hpp>
#include <google/protobuf/descriptor.h>
#include "mediapipe/framework/calculator.pb.h"
#include "mediapipe/examples/desktop/pipeline_output.pb.h"

/// this is C API for operating a mediapipe pipeline (or rather, the only one we operate)
/// it wraps around our C++ HandsPipelineOperator class by supplying pure C functions either
/// generate, destroy, or take as input a handle, representing an instance of the latter C++ class,
/// such that the C++ object is fully operated by the C-style function calls provided by it.

void check_protobuf_linking() {
    // force the protocol buffers registration process to happen at initialization of the C API (rather than on first protobuf object access)
    // in order to fail early and informatively if the protobuf types are missing or not the same version as those used during compilation,
    // which may happen due to imprecise linking strategies which are easy to get in particular when consuming the C API via its bazel built
    // shared library, and somewhat less so in pure bazel built executables.
    //
    // the most staggering and common fail scenario leading to this is when the protocol buffers version used during compilation,
    // e.g. 3.19.x, is different than the one loaded by the system loader for the executable linked against the C API shared library,
    // the unmatching version perhaps coming from the loader dynamincally loading a different version of protocol buffers from the system
    // registered one (libprotobuf.so) which may be of a different version, as said, than than compiled with.
    //
    // another fail scenario is that only specific protocol buffers types required by the compiled code are missing at runtime,
    // e.g. because they have been not inlucded in linking, perhaps due to a missing bazel dependencies path of alwayslink=1
    // bazel build definitions from the C API shared library target down to those types.
    //
    // protobuf descriptor tables are generated by the protobuf compiler to contain metadata for message types,
    // which must be matched by symbols loaded by the loader before passing to the executable's main, when actually running.
    // any version incompatibility will be tripped upon at this stage.
    // ---------------------------------------------------------------
    // this checking of the inclusion of symbols for all necessary protobuf types is trigggered here by explicitly referencing the protobuf descriptor
    // table only for the sake of forcing early and informative failure in case any of their expected symbols are missing. the purpose of this is to fail
    // in an informative manner, in case the symbols expected at runtime arising in the compilation of the C API ― are some how either missing,
    // or are of a different version than those used during compilation of the C API ― at runtime.
    // this all is harder to check by probing the built executables directly, the linker LD_DEBUG=libs environment variable is helpful,
    // and so are lddtree and nm, but probing at that level leaves you with only a swiss-cheese assortment of probing features,  
    // whereas checking what fails to load at runtime is more bottom-line informative.
    fprintf(stderr, "[pipeline C API protobuf initialization] forcing early protobuf initialization ...\n");

    // Step 0: Explicitly reference descriptor table symbols to force registration.
    fprintf(stderr, "[pipeline C API protobuf initialization] about to reference the protobuf descriptor tables ...\n");
    extern const ::google::protobuf::internal::DescriptorTable descriptor_table_mediapipe_2fframework_2fcalculator_2eproto;
    (void)descriptor_table_mediapipe_2fframework_2fcalculator_2eproto;
    extern const ::google::protobuf::internal::DescriptorTable descriptor_table_mediapipe_2fexamples_2fdesktop_2fpipeline_5foutput_2eproto;
    (void)descriptor_table_mediapipe_2fexamples_2fdesktop_2fpipeline_5foutput_2eproto;
    fprintf(stderr, "[pipeline C API protobuf initialization] descriptor tables successfully referenced.\n");

    // Step 1: Now safe to call DescriptorPool::generated_pool()
    fprintf(stderr, "[pipeline C API protobuf initialization] about to call DescriptorPool::generated_pool()\n");
    auto* pool = ::google::protobuf::DescriptorPool::generated_pool();
    if (pool == nullptr) {
        fprintf(stderr, "[pipeline C API protobuf initialization] FATAL: DescriptorPool::generated_pool() returned nullptr!\n");
        abort();
    }

    // Step 2: Probe the pool for some key expected file descriptors
    fprintf(stderr, "[pipeline C API protobuf initialization] about to check for specific file descriptors in the pool ...\n");
    const char* calculator_proto_name = "mediapipe/framework/calculator.proto";
    if (pool->FindFileByName(calculator_proto_name) == nullptr) {
        fprintf(stderr, "[C API] FATAL: DescriptorPool missing file: %s\n", calculator_proto_name);
        abort();
    }
    const char* pipeline_output_proto_name = "mediapipe/examples/desktop/pipeline_output.proto";
    if (pool->FindFileByName(pipeline_output_proto_name) == nullptr) {
        fprintf(stderr, "[pipeline C API protobuf initialization] FATAL: DescriptorPool missing file: %s\n", pipeline_output_proto_name);
        abort();
    }

    // Step 3: Finally reference some key message descriptors
    fprintf(stderr, "Step 3: Checking CalculatorGraphConfig descriptor\n");
    if (hand_tracking_mp_lean::CalculatorGraphConfig::descriptor() == nullptr) {
        fprintf(stderr, "[pipeline C API protobuf initialization] FATAL: CalculatorGraphConfig descriptor not registered!\n");
        abort();
    }
    if (hand_tracking_mp_lean::PipelineOutputData::descriptor() == nullptr) {
        fprintf(stderr, "[pipeline C API protobuf initialization] FATAL: PipelineOutputData descriptor not registered!\n");
        abort();
    }
}

void safe_init_protobuf() {
    GOOGLE_PROTOBUF_VERIFY_VERSION; // not sure why this macro didn't ring the bell in earlier mismatch cases
    check_protobuf_linking();
}

// C-style error state management (thread-local)
static thread_local std::string g_last_error;
static void set_last_error(const std::string& err) { g_last_error = err; }
extern "C" const char* hands_pipeline_operator_get_last_error() { return g_last_error.c_str(); }

/// this struct is the heart of enabling the API.
/// it is a C++ struct type definition encapsulating only a pointer to a HandsPipelineOperator instance,
/// which is only used by the C++ part of the C api, and on the C facade of the api is seen as merely
/// an opaque pointer (void *) of type HandsPipelineOperatorHandle.
///
/// how this plays out in more detail:
///
/// C facade:
///   the C api consumer only sees a HandsPipelineOperatorOpaqueHandle (a.k.a in this context an opaque handler)
///   which it gets back from calling the C api's instantiation proxy function hands_pipeline_operator_create.
///   the C api consumer then passes that opaque handle back on each subsequent api call. for the c code
///   it's just a pointer.
///
/// API implementation functions:
///   within the function implementations of the C api, that opaque handler is cast back
///   to this C++ struct type thus enabling the C api functions to operate the C++ object.
///   this pattern enables C code to operate a C++ object.
struct CppInstanceWrapper {
    std::unique_ptr<hand_tracking_mp_lean::HandsPipelineOperator> cpp_impl;
};

extern "C" HandsPipelineOperatorOpaqueHandle hands_pipeline_operator_create(
    const uint max_hands_to_track,
    const char* graph_file_path,
    const char* output_streams_csv) {

    safe_init_protobuf();

    set_last_error("");
    std::vector<std::string> output_streams;
    std::istringstream ss(output_streams_csv ? output_streams_csv : "");
    std::string item;
    while (std::getline(ss, item, ',')) {
        if (!item.empty()) output_streams.push_back(item);
    }
    auto* cpp_instance_wrapper = new CppInstanceWrapper;
    auto status_or_op = hand_tracking_mp_lean::HandsPipelineOperator::Create(max_hands_to_track, std::string(graph_file_path), output_streams);
    if (!status_or_op.ok()) {
        set_last_error(std::string(status_or_op.status().message()));
        delete cpp_instance_wrapper;
        return nullptr;
    }
    cpp_instance_wrapper->cpp_impl = std::move(status_or_op.value());
    return cpp_instance_wrapper;
}

extern "C" int hands_pipeline_operator_push_image(
    HandsPipelineOperatorOpaqueHandle opaque_handle,
    const uint8_t* image_data, int width, int height, int channels,
    int64_t timestamp_us) {

    auto* cpp_instance_wrapper = static_cast<CppInstanceWrapper*>(opaque_handle);  // casts the opaque pointer back to C++

    set_last_error("");
    if (!opaque_handle || !image_data || width <= 0 || height <= 0 || channels <= 0) {
        set_last_error("Invalid arguments to push_image");
        return -1;
    }

    cv::Mat input_frame(height, width, channels == 3 ? CV_8UC3 : CV_8UC1, (void*)image_data);
    cv::Mat frame_copy = input_frame.clone();  // copy to simplistically avoid lifetime issues for now
    absl::Status status = cpp_instance_wrapper->cpp_impl->PushImage(frame_copy, timestamp_us);
    if (!status.ok()) {
        set_last_error(std::string(status.message()));
        return -1;
    }
    return 0;
}

/// the output is returned as serialized protobuf (into char** output_data)
/// just because the original pipeline did so, and because we have diffing
/// code for protobuf.
extern "C" int hands_pipeline_operator_wait_for_output(
    HandsPipelineOperatorOpaqueHandle opaque_handle,
    int frame_number,
    char** output_data, size_t* output_size) {
    set_last_error("");
    if (!opaque_handle || !output_data || !output_size) {
        set_last_error("Invalid arguments to wait_for_output");
        return -1;
    }
    auto* cpp_instance_wrapper = static_cast<CppInstanceWrapper*>(opaque_handle);  // casts the opaque pointer back to C++
    hand_tracking_mp_lean::PipelineOutputData output;
    absl::Status status = cpp_instance_wrapper->cpp_impl->WaitForOutput(&output, frame_number);
    if (!status.ok()) {
        set_last_error(std::string(status.message()));
        return -1;
    }
    std::string serialized;
    if (!output.SerializeToString(&serialized)) {
        set_last_error("Failed to serialize PipelineOutputData");
        return -1;
    }
    *output_size = serialized.size();
    *output_data = (char*)malloc(*output_size);
    if (!*output_data) {
        set_last_error("Failed to allocate output buffer");
        return -1;
    }
    memcpy(*output_data, serialized.data(), *output_size);
    return 0;
}

// destruct a created instance, this function is internal and not exposed as API
static void hands_pipeline_operator_destroy(HandsPipelineOperatorOpaqueHandle opaque_handle) {
    /// delete runs the destructor of the struct which opaque_handle points at,
    /// after calling the destructor of its contained C++ instance.
    if (opaque_handle) delete static_cast<CppInstanceWrapper*>(opaque_handle);
}

/// call the underlying C++ class's finalization method, and then free (delete) its C++ instance from memory.
extern "C" int hands_pipeline_operator_finalize(HandsPipelineOperatorOpaqueHandle opaque_handle) {
    set_last_error("");
    if (!opaque_handle) {
        set_last_error("nullptr passed to finalize");
        return -1;
    }
    auto* cpp_instance_wrapper = static_cast<CppInstanceWrapper*>(opaque_handle);  // casts the opaque pointer back to C++
    absl::Status status = cpp_instance_wrapper->cpp_impl->Finalize();
    hands_pipeline_operator_destroy(opaque_handle);

    if (!status.ok()) {
        set_last_error(std::string(status.message()));
        return -1;
    }

    return 0;
}
