# runs the hands pipeline over an input file, writing its outputs to a protobuf output file.
# adapted from hands_test.py, which looks for a testdata directory that isn't part of the original mediapipe repository ...

import os
import sys
import cv2
import numpy as np
from pathlib import Path

# implement safe importing of mediapipe. meaning, one that will successfully import it from the installed mediapipe package,
# rather than fail to import it when running in debug mode via pydev:
#
# Traceback (most recent call last):
#   File "pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1648, in _exec
#     pydev_imports.execfile(file, globals, locals)  # execute the script
#     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
#     exec(compile(contents+"\n", file, 'exec'), glob, loc)
#   File "/home/usermediapipe/hand_tracking_pipeline_run.py", line 38, in <module>
#     from mediapipe.python.solutions import hands as mp_hands
#   File "/home/usermediapipe/mediapipe/__init__.py", line 15, in <module>
#     from mediapipe.python import *
#   File "/home/usermediapipe/mediapipe/python/__init__.py", line 17, in <module>
#     from mediapipe.python._framework_bindings import model_ckpt_util
# ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
#
# why we need this?
# with a plain python interpreter we can use -P for this behavior, but for debugging python mains reliant on pydev.py,
# which most python IDE use for debugging python, we have to code this defensive behavior in our main itself, since pydev does not handle or safely pass -P
# to the actual interpeter that is launches or itself is, and our mains do expect to run from our project root,
# which always contains a "mediapipe" source directory in this fork of mediapipe, which must be ignored
# by import statements when run from the project root.
# ----------------------------------------------------
# alternative no-code solution:
# env variable PYTHONSAFEPATH=1 works but only with the regular python interpreter, not wity pydev 
# in mediapipe docs they recommend just exiting the project directory before running its mains, instead.
# ------------------------------------------------------------------------------------------------------
# current solution:
# before importing mediapipe ―
# identify the absolute path of the directory containing the our script running, and remove that directory (which is also normally the working directory)
# from python's sys.path, so that python does not try importing packages from subdirectories which have their name, which is the case when you are running
# python in the current project ― whereas the subdirectories should be thought of (despite it being python) only source folders in this project.
current_script_dir = os.path.dirname(os.path.abspath(__file__))
appearances = 0
for path in sys.path:
    # Note: the following code is not it will only filter out instances of the current path from sys.path which are absolute (and not relative) paths.
    #       not sure if sys.path would ever use relative paths.
    if os.path.abspath(path) == current_script_dir:
        appearances += 1
if appearances > 0:
    for i in range(appearances):
        sys.path.remove(current_script_dir)
    print("INFO: the working directory will be ignored by import statements, by removing it from python's sys.path for the current run, to avoid it overshadowing the environment installed mediapipe package for import statements.")

from mediapipe.python.solutions import hands as mp_hands
# these imports may still be flagged as unknown symbols by the IDE,
# since the IDE too may typically look for the packages under the project root's subdirectories first, rather than where the package
# sources have been installed by pip install, which is where these generated files actually are after you've pip installed mediapipe.
# (configuring PyCharm to acknowledge their location (e.g. .venv/lib/python3.12/site-packages) as a source root directory doesn't seem
# to avoid that, even if the mediapipe subdirectory is marked for it as "excluded").
# the "import and del" pattern in mediapipe/__init__.py, which is oddly dynamically generated by setup.py to have constant contents
# (see _write__init__source_file in setup.py) may or may not also contribute to not properly exposing them.
# it's best to avoid this quirk only affecting IDE flagging of this small set of proto-generated symbols,
# than dive deep on it for now ― you can easily view the same named proto files, and the generated same
# named modules are just under the venv after you have pip installed ...
from mediapipe.framework.formats import landmark_pb2, classification_pb2, rect_pb2, detection_pb2
from mediapipe.examples.desktop import pipeline_output_pb2

OUTPUT_FILE_PATH = "output_data_python.pb"

num_landmarks=21
num_dimensions=3

def write_delimited_message(pb_file, message):
    # no python library implementation for this in python https://chatgpt.com/s/t_68de7b5db2bc8191a472dc39f7af2c4a
    # (only in cpp, so we roll our chatgpt own)
    data = message.SerializeToString()
    length = len(data)
    # Write length as protobuf varint
    while True:
        to_write = length & 0x7F
        length >>= 7
        if length:
            pb_file.write(bytes([to_write | 0x80]))
        else:
            pb_file.write(bytes([to_write]))
            break
    pb_file.write(data)

def run_for_video(input_video, max_num_hands, model_complexity=1):
    # Predict pose landmarks for each frame.
    video_cap = cv2.VideoCapture(input_video)
    total_frames = int(video_cap.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"Processing video {input_video} consisting of {total_frames} frames")
    landmarks_per_frame = []
    w_landmarks_per_frame = []
    processed_frames = 0
    frame_idx = 0

    # Open file in write binary mode to overwrite any existing file
    with open(OUTPUT_FILE_PATH, "wb") as pb_file:
        with mp_hands.Hands(
                static_image_mode = False,
                max_num_hands = max_num_hands,
                model_complexity = model_complexity,
                min_detection_confidence = 0.5
                ) as hands:
            while True:
                success, input_frame = video_cap.read()
                if not success:
                    if frame_idx < total_frames:
                        raise RuntimeError(f"Bad/corrupt frame encountered at frame {frame_idx} (0-based index). Stopping early.")
                    break

                # put the output into a protobuf message for file writing
                output_msg = pipeline_output_pb2.PipelineOutputData()
                output_msg.frame_number = frame_idx
                processed_frames += 1
                input_frame = cv2.cvtColor(input_frame, cv2.COLOR_BGR2RGB)
                frame_shape = input_frame.shape
                result = hands.process(image = input_frame)

                frame_landmarks = np.empty([max_num_hands, num_landmarks, num_dimensions]) * np.nan
                frame_w_landmarks = np.empty([max_num_hands, num_landmarks, num_dimensions]) * np.nan

                if result.multi_hand_landmarks:
                    for landmarks in result.multi_hand_landmarks:
                        output_msg.multi_hand_landmarks.append(landmarks)

                if result.multi_hand_world_landmarks:
                    for w_landmarks in result.multi_hand_world_landmarks:
                        output_msg.multi_hand_world_landmarks.append(w_landmarks)

                if result.multi_handedness:
                    for handedness in result.multi_handedness:
                        output_msg.multi_handedness.append(handedness)

                # Optionally: hand_rects_from_palm_detections if available
                # if result.hand_rects_from_palm_detections:
                #     for rect in result.hand_rects_from_palm_detections:
                #         output_msg.hand_rects_from_palm_detections.append(rect)

                # Write as delimited protobuf message
                write_delimited_message(pb_file, output_msg)
                frame_idx += 1

    print(f"Writing completed: {processed_frames} frames processed and saved to {os.path.abspath(OUTPUT_FILE_PATH)}")

    if processed_frames < total_frames:
        raise RuntimeError(f"Video processing stopped early: processed {processed_frames} out of {total_frames} frames. Possible bad/corrupt frame encountered.")


if __name__ == '__main__':
    import sys
    if not sys.argv[1:] or len(sys.argv) > 2:
        print("Usage: python -P hand_tracking_pipeline_run.py <input-video-path>")
        sys.exit(1)
    if not Path(sys.argv[1]).exists():
        print(f"{sys.argv[1]} does not exist")
        sys.exit(1)

    input_video = sys.argv[1]

    run_for_video(input_video, max_num_hands=2)

    # The following stderr output is expected at the start of the run:
    # INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
    # WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
    # W0000 00:00:1758560081.963286 2425952 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
    # W0000 00:00:1758560081.975544 2425952 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
    # W0000 00:00:1758560082.720623 2425968 landmark_projection_calculator.cc:78] Using NORM_RECT without IMAGE_DIMENSIONS is only supported for the square ROI. Provide IMAGE_DIMENSIONS or use PROJECTION_MATRIX.
