#![allow(unused_imports, unused_parens, dead_code, renamed_and_removed_lints, mismatched_lifetime_syntaxes)]
//! Protobuf module for PipelineOutputData
// This file is auto-generated by prost_build in build.rs
// The generated code will be available as crate::proto::pipeline_output
pub mod pipeline_output;
pub mod landmark;
pub mod classification;
pub mod rect;
