# Copyright 2019 - 2022 The MediaPipe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: this file is currently dynamically generated by pip installing (see setup.py) and thus may not be the original git borne version of itself.

from hand_tracking_mp_lean.python import *
import hand_tracking_mp_lean.python.solutions as solutions 
import hand_tracking_mp_lean.tasks.python as tasks

del framework
del gpu
del modules
del python
del hand_tracking_mp_lean
del util
__version__ = '0+207ee5e37'
