// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `mediapipe/framework/formats/landmark.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:mediapipe.Landmark)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Landmark {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.Landmark.x)
    pub x: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.Landmark.y)
    pub y: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.Landmark.z)
    pub z: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.Landmark.visibility)
    pub visibility: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.Landmark.presence)
    pub presence: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.Landmark.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Landmark {
    fn default() -> &'a Landmark {
        <Landmark as ::protobuf::Message>::default_instance()
    }
}

impl Landmark {
    pub fn new() -> Landmark {
        ::std::default::Default::default()
    }

    // optional float x = 1;

    pub fn x(&self) -> f32 {
        self.x.unwrap_or(0.)
    }

    pub fn clear_x(&mut self) {
        self.x = ::std::option::Option::None;
    }

    pub fn has_x(&self) -> bool {
        self.x.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: f32) {
        self.x = ::std::option::Option::Some(v);
    }

    // optional float y = 2;

    pub fn y(&self) -> f32 {
        self.y.unwrap_or(0.)
    }

    pub fn clear_y(&mut self) {
        self.y = ::std::option::Option::None;
    }

    pub fn has_y(&self) -> bool {
        self.y.is_some()
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: f32) {
        self.y = ::std::option::Option::Some(v);
    }

    // optional float z = 3;

    pub fn z(&self) -> f32 {
        self.z.unwrap_or(0.)
    }

    pub fn clear_z(&mut self) {
        self.z = ::std::option::Option::None;
    }

    pub fn has_z(&self) -> bool {
        self.z.is_some()
    }

    // Param is passed by value, moved
    pub fn set_z(&mut self, v: f32) {
        self.z = ::std::option::Option::Some(v);
    }

    // optional float visibility = 4;

    pub fn visibility(&self) -> f32 {
        self.visibility.unwrap_or(0.)
    }

    pub fn clear_visibility(&mut self) {
        self.visibility = ::std::option::Option::None;
    }

    pub fn has_visibility(&self) -> bool {
        self.visibility.is_some()
    }

    // Param is passed by value, moved
    pub fn set_visibility(&mut self, v: f32) {
        self.visibility = ::std::option::Option::Some(v);
    }

    // optional float presence = 5;

    pub fn presence(&self) -> f32 {
        self.presence.unwrap_or(0.)
    }

    pub fn clear_presence(&mut self) {
        self.presence = ::std::option::Option::None;
    }

    pub fn has_presence(&self) -> bool {
        self.presence.is_some()
    }

    // Param is passed by value, moved
    pub fn set_presence(&mut self, v: f32) {
        self.presence = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "x",
            |m: &Landmark| { &m.x },
            |m: &mut Landmark| { &mut m.x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "y",
            |m: &Landmark| { &m.y },
            |m: &mut Landmark| { &mut m.y },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "z",
            |m: &Landmark| { &m.z },
            |m: &mut Landmark| { &mut m.z },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "visibility",
            |m: &Landmark| { &m.visibility },
            |m: &mut Landmark| { &mut m.visibility },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "presence",
            |m: &Landmark| { &m.presence },
            |m: &mut Landmark| { &mut m.presence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Landmark>(
            "Landmark",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Landmark {
    const NAME: &'static str = "Landmark";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.x = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.y = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.z = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.visibility = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.presence = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x {
            my_size += 1 + 4;
        }
        if let Some(v) = self.y {
            my_size += 1 + 4;
        }
        if let Some(v) = self.z {
            my_size += 1 + 4;
        }
        if let Some(v) = self.visibility {
            my_size += 1 + 4;
        }
        if let Some(v) = self.presence {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.y {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.z {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.visibility {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.presence {
            os.write_float(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Landmark {
        Landmark::new()
    }

    fn clear(&mut self) {
        self.x = ::std::option::Option::None;
        self.y = ::std::option::Option::None;
        self.z = ::std::option::Option::None;
        self.visibility = ::std::option::Option::None;
        self.presence = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Landmark {
        static instance: Landmark = Landmark {
            x: ::std::option::Option::None,
            y: ::std::option::Option::None,
            z: ::std::option::Option::None,
            visibility: ::std::option::Option::None,
            presence: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Landmark {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Landmark").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Landmark {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Landmark {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.LandmarkList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LandmarkList {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.LandmarkList.landmark)
    pub landmark: ::std::vec::Vec<Landmark>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.LandmarkList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LandmarkList {
    fn default() -> &'a LandmarkList {
        <LandmarkList as ::protobuf::Message>::default_instance()
    }
}

impl LandmarkList {
    pub fn new() -> LandmarkList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "landmark",
            |m: &LandmarkList| { &m.landmark },
            |m: &mut LandmarkList| { &mut m.landmark },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LandmarkList>(
            "LandmarkList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LandmarkList {
    const NAME: &'static str = "LandmarkList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.landmark.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.landmark {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.landmark {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LandmarkList {
        LandmarkList::new()
    }

    fn clear(&mut self) {
        self.landmark.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LandmarkList {
        static instance: LandmarkList = LandmarkList {
            landmark: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LandmarkList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LandmarkList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LandmarkList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LandmarkList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.LandmarkListCollection)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LandmarkListCollection {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.LandmarkListCollection.landmark_list)
    pub landmark_list: ::std::vec::Vec<LandmarkList>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.LandmarkListCollection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LandmarkListCollection {
    fn default() -> &'a LandmarkListCollection {
        <LandmarkListCollection as ::protobuf::Message>::default_instance()
    }
}

impl LandmarkListCollection {
    pub fn new() -> LandmarkListCollection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "landmark_list",
            |m: &LandmarkListCollection| { &m.landmark_list },
            |m: &mut LandmarkListCollection| { &mut m.landmark_list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LandmarkListCollection>(
            "LandmarkListCollection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LandmarkListCollection {
    const NAME: &'static str = "LandmarkListCollection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.landmark_list.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.landmark_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.landmark_list {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LandmarkListCollection {
        LandmarkListCollection::new()
    }

    fn clear(&mut self) {
        self.landmark_list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LandmarkListCollection {
        static instance: LandmarkListCollection = LandmarkListCollection {
            landmark_list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LandmarkListCollection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LandmarkListCollection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LandmarkListCollection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LandmarkListCollection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.NormalizedLandmark)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NormalizedLandmark {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmark.x)
    pub x: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmark.y)
    pub y: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmark.z)
    pub z: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmark.visibility)
    pub visibility: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmark.presence)
    pub presence: ::std::option::Option<f32>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.NormalizedLandmark.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NormalizedLandmark {
    fn default() -> &'a NormalizedLandmark {
        <NormalizedLandmark as ::protobuf::Message>::default_instance()
    }
}

impl NormalizedLandmark {
    pub fn new() -> NormalizedLandmark {
        ::std::default::Default::default()
    }

    // optional float x = 1;

    pub fn x(&self) -> f32 {
        self.x.unwrap_or(0.)
    }

    pub fn clear_x(&mut self) {
        self.x = ::std::option::Option::None;
    }

    pub fn has_x(&self) -> bool {
        self.x.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x(&mut self, v: f32) {
        self.x = ::std::option::Option::Some(v);
    }

    // optional float y = 2;

    pub fn y(&self) -> f32 {
        self.y.unwrap_or(0.)
    }

    pub fn clear_y(&mut self) {
        self.y = ::std::option::Option::None;
    }

    pub fn has_y(&self) -> bool {
        self.y.is_some()
    }

    // Param is passed by value, moved
    pub fn set_y(&mut self, v: f32) {
        self.y = ::std::option::Option::Some(v);
    }

    // optional float z = 3;

    pub fn z(&self) -> f32 {
        self.z.unwrap_or(0.)
    }

    pub fn clear_z(&mut self) {
        self.z = ::std::option::Option::None;
    }

    pub fn has_z(&self) -> bool {
        self.z.is_some()
    }

    // Param is passed by value, moved
    pub fn set_z(&mut self, v: f32) {
        self.z = ::std::option::Option::Some(v);
    }

    // optional float visibility = 4;

    pub fn visibility(&self) -> f32 {
        self.visibility.unwrap_or(0.)
    }

    pub fn clear_visibility(&mut self) {
        self.visibility = ::std::option::Option::None;
    }

    pub fn has_visibility(&self) -> bool {
        self.visibility.is_some()
    }

    // Param is passed by value, moved
    pub fn set_visibility(&mut self, v: f32) {
        self.visibility = ::std::option::Option::Some(v);
    }

    // optional float presence = 5;

    pub fn presence(&self) -> f32 {
        self.presence.unwrap_or(0.)
    }

    pub fn clear_presence(&mut self) {
        self.presence = ::std::option::Option::None;
    }

    pub fn has_presence(&self) -> bool {
        self.presence.is_some()
    }

    // Param is passed by value, moved
    pub fn set_presence(&mut self, v: f32) {
        self.presence = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "x",
            |m: &NormalizedLandmark| { &m.x },
            |m: &mut NormalizedLandmark| { &mut m.x },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "y",
            |m: &NormalizedLandmark| { &m.y },
            |m: &mut NormalizedLandmark| { &mut m.y },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "z",
            |m: &NormalizedLandmark| { &m.z },
            |m: &mut NormalizedLandmark| { &mut m.z },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "visibility",
            |m: &NormalizedLandmark| { &m.visibility },
            |m: &mut NormalizedLandmark| { &mut m.visibility },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "presence",
            |m: &NormalizedLandmark| { &m.presence },
            |m: &mut NormalizedLandmark| { &mut m.presence },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NormalizedLandmark>(
            "NormalizedLandmark",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NormalizedLandmark {
    const NAME: &'static str = "NormalizedLandmark";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.x = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.y = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.z = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.visibility = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.presence = ::std::option::Option::Some(is.read_float()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x {
            my_size += 1 + 4;
        }
        if let Some(v) = self.y {
            my_size += 1 + 4;
        }
        if let Some(v) = self.z {
            my_size += 1 + 4;
        }
        if let Some(v) = self.visibility {
            my_size += 1 + 4;
        }
        if let Some(v) = self.presence {
            my_size += 1 + 4;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.y {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.z {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.visibility {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.presence {
            os.write_float(5, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NormalizedLandmark {
        NormalizedLandmark::new()
    }

    fn clear(&mut self) {
        self.x = ::std::option::Option::None;
        self.y = ::std::option::Option::None;
        self.z = ::std::option::Option::None;
        self.visibility = ::std::option::Option::None;
        self.presence = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NormalizedLandmark {
        static instance: NormalizedLandmark = NormalizedLandmark {
            x: ::std::option::Option::None,
            y: ::std::option::Option::None,
            z: ::std::option::Option::None,
            visibility: ::std::option::Option::None,
            presence: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NormalizedLandmark {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NormalizedLandmark").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NormalizedLandmark {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NormalizedLandmark {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.NormalizedLandmarkList)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NormalizedLandmarkList {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmarkList.landmark)
    pub landmark: ::std::vec::Vec<NormalizedLandmark>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.NormalizedLandmarkList.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NormalizedLandmarkList {
    fn default() -> &'a NormalizedLandmarkList {
        <NormalizedLandmarkList as ::protobuf::Message>::default_instance()
    }
}

impl NormalizedLandmarkList {
    pub fn new() -> NormalizedLandmarkList {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "landmark",
            |m: &NormalizedLandmarkList| { &m.landmark },
            |m: &mut NormalizedLandmarkList| { &mut m.landmark },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NormalizedLandmarkList>(
            "NormalizedLandmarkList",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NormalizedLandmarkList {
    const NAME: &'static str = "NormalizedLandmarkList";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.landmark.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.landmark {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.landmark {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NormalizedLandmarkList {
        NormalizedLandmarkList::new()
    }

    fn clear(&mut self) {
        self.landmark.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NormalizedLandmarkList {
        static instance: NormalizedLandmarkList = NormalizedLandmarkList {
            landmark: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NormalizedLandmarkList {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NormalizedLandmarkList").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NormalizedLandmarkList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NormalizedLandmarkList {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.NormalizedLandmarkListCollection)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NormalizedLandmarkListCollection {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.NormalizedLandmarkListCollection.landmark_list)
    pub landmark_list: ::std::vec::Vec<NormalizedLandmarkList>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.NormalizedLandmarkListCollection.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NormalizedLandmarkListCollection {
    fn default() -> &'a NormalizedLandmarkListCollection {
        <NormalizedLandmarkListCollection as ::protobuf::Message>::default_instance()
    }
}

impl NormalizedLandmarkListCollection {
    pub fn new() -> NormalizedLandmarkListCollection {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "landmark_list",
            |m: &NormalizedLandmarkListCollection| { &m.landmark_list },
            |m: &mut NormalizedLandmarkListCollection| { &mut m.landmark_list },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NormalizedLandmarkListCollection>(
            "NormalizedLandmarkListCollection",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NormalizedLandmarkListCollection {
    const NAME: &'static str = "NormalizedLandmarkListCollection";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.landmark_list.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.landmark_list {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.landmark_list {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NormalizedLandmarkListCollection {
        NormalizedLandmarkListCollection::new()
    }

    fn clear(&mut self) {
        self.landmark_list.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NormalizedLandmarkListCollection {
        static instance: NormalizedLandmarkListCollection = NormalizedLandmarkListCollection {
            landmark_list: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NormalizedLandmarkListCollection {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NormalizedLandmarkListCollection").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NormalizedLandmarkListCollection {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NormalizedLandmarkListCollection {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n*mediapipe/framework/formats/landmark.proto\x12\tmediapipe\"p\n\x08Lan\
    dmark\x12\x0c\n\x01x\x18\x01\x20\x01(\x02R\x01x\x12\x0c\n\x01y\x18\x02\
    \x20\x01(\x02R\x01y\x12\x0c\n\x01z\x18\x03\x20\x01(\x02R\x01z\x12\x1e\n\
    \nvisibility\x18\x04\x20\x01(\x02R\nvisibility\x12\x1a\n\x08presence\x18\
    \x05\x20\x01(\x02R\x08presence\"?\n\x0cLandmarkList\x12/\n\x08landmark\
    \x18\x01\x20\x03(\x0b2\x13.mediapipe.LandmarkR\x08landmark\"V\n\x16Landm\
    arkListCollection\x12<\n\rlandmark_list\x18\x01\x20\x03(\x0b2\x17.mediap\
    ipe.LandmarkListR\x0clandmarkList\"z\n\x12NormalizedLandmark\x12\x0c\n\
    \x01x\x18\x01\x20\x01(\x02R\x01x\x12\x0c\n\x01y\x18\x02\x20\x01(\x02R\
    \x01y\x12\x0c\n\x01z\x18\x03\x20\x01(\x02R\x01z\x12\x1e\n\nvisibility\
    \x18\x04\x20\x01(\x02R\nvisibility\x12\x1a\n\x08presence\x18\x05\x20\x01\
    (\x02R\x08presence\"S\n\x16NormalizedLandmarkList\x129\n\x08landmark\x18\
    \x01\x20\x03(\x0b2\x1d.mediapipe.NormalizedLandmarkR\x08landmark\"j\n\
    \x20NormalizedLandmarkListCollection\x12F\n\rlandmark_list\x18\x01\x20\
    \x03(\x0b2!.mediapipe.NormalizedLandmarkListR\x0clandmarkListB3\n\"com.g\
    oogle.mediapipe.formats.protoB\rLandmarkProto\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(6);
            messages.push(Landmark::generated_message_descriptor_data());
            messages.push(LandmarkList::generated_message_descriptor_data());
            messages.push(LandmarkListCollection::generated_message_descriptor_data());
            messages.push(NormalizedLandmark::generated_message_descriptor_data());
            messages.push(NormalizedLandmarkList::generated_message_descriptor_data());
            messages.push(NormalizedLandmarkListCollection::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
