// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 3.21.12
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `mediapipe/framework/formats/rect.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:mediapipe.Rect)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct Rect {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.Rect.x_center)
    pub x_center: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:mediapipe.Rect.y_center)
    pub y_center: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:mediapipe.Rect.height)
    pub height: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:mediapipe.Rect.width)
    pub width: ::std::option::Option<i32>,
    // @@protoc_insertion_point(field:mediapipe.Rect.rotation)
    pub rotation: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.Rect.rect_id)
    pub rect_id: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.Rect.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a Rect {
    fn default() -> &'a Rect {
        <Rect as ::protobuf::Message>::default_instance()
    }
}

impl Rect {
    pub fn new() -> Rect {
        ::std::default::Default::default()
    }

    // required int32 x_center = 1;

    pub fn x_center(&self) -> i32 {
        self.x_center.unwrap_or(0)
    }

    pub fn clear_x_center(&mut self) {
        self.x_center = ::std::option::Option::None;
    }

    pub fn has_x_center(&self) -> bool {
        self.x_center.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x_center(&mut self, v: i32) {
        self.x_center = ::std::option::Option::Some(v);
    }

    // required int32 y_center = 2;

    pub fn y_center(&self) -> i32 {
        self.y_center.unwrap_or(0)
    }

    pub fn clear_y_center(&mut self) {
        self.y_center = ::std::option::Option::None;
    }

    pub fn has_y_center(&self) -> bool {
        self.y_center.is_some()
    }

    // Param is passed by value, moved
    pub fn set_y_center(&mut self, v: i32) {
        self.y_center = ::std::option::Option::Some(v);
    }

    // required int32 height = 3;

    pub fn height(&self) -> i32 {
        self.height.unwrap_or(0)
    }

    pub fn clear_height(&mut self) {
        self.height = ::std::option::Option::None;
    }

    pub fn has_height(&self) -> bool {
        self.height.is_some()
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: i32) {
        self.height = ::std::option::Option::Some(v);
    }

    // required int32 width = 4;

    pub fn width(&self) -> i32 {
        self.width.unwrap_or(0)
    }

    pub fn clear_width(&mut self) {
        self.width = ::std::option::Option::None;
    }

    pub fn has_width(&self) -> bool {
        self.width.is_some()
    }

    // Param is passed by value, moved
    pub fn set_width(&mut self, v: i32) {
        self.width = ::std::option::Option::Some(v);
    }

    // optional float rotation = 5;

    pub fn rotation(&self) -> f32 {
        self.rotation.unwrap_or(0.0f32)
    }

    pub fn clear_rotation(&mut self) {
        self.rotation = ::std::option::Option::None;
    }

    pub fn has_rotation(&self) -> bool {
        self.rotation.is_some()
    }

    // Param is passed by value, moved
    pub fn set_rotation(&mut self, v: f32) {
        self.rotation = ::std::option::Option::Some(v);
    }

    // optional int64 rect_id = 6;

    pub fn rect_id(&self) -> i64 {
        self.rect_id.unwrap_or(0)
    }

    pub fn clear_rect_id(&mut self) {
        self.rect_id = ::std::option::Option::None;
    }

    pub fn has_rect_id(&self) -> bool {
        self.rect_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_rect_id(&mut self, v: i64) {
        self.rect_id = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "x_center",
            |m: &Rect| { &m.x_center },
            |m: &mut Rect| { &mut m.x_center },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "y_center",
            |m: &Rect| { &m.y_center },
            |m: &mut Rect| { &mut m.y_center },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "height",
            |m: &Rect| { &m.height },
            |m: &mut Rect| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "width",
            |m: &Rect| { &m.width },
            |m: &mut Rect| { &mut m.width },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "rotation",
            |m: &Rect| { &m.rotation },
            |m: &mut Rect| { &mut m.rotation },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "rect_id",
            |m: &Rect| { &m.rect_id },
            |m: &mut Rect| { &mut m.rect_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<Rect>(
            "Rect",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for Rect {
    const NAME: &'static str = "Rect";

    fn is_initialized(&self) -> bool {
        if self.x_center.is_none() {
            return false;
        }
        if self.y_center.is_none() {
            return false;
        }
        if self.height.is_none() {
            return false;
        }
        if self.width.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.x_center = ::std::option::Option::Some(is.read_int32()?);
                },
                16 => {
                    self.y_center = ::std::option::Option::Some(is.read_int32()?);
                },
                24 => {
                    self.height = ::std::option::Option::Some(is.read_int32()?);
                },
                32 => {
                    self.width = ::std::option::Option::Some(is.read_int32()?);
                },
                45 => {
                    self.rotation = ::std::option::Option::Some(is.read_float()?);
                },
                48 => {
                    self.rect_id = ::std::option::Option::Some(is.read_int64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x_center {
            my_size += ::protobuf::rt::int32_size(1, v);
        }
        if let Some(v) = self.y_center {
            my_size += ::protobuf::rt::int32_size(2, v);
        }
        if let Some(v) = self.height {
            my_size += ::protobuf::rt::int32_size(3, v);
        }
        if let Some(v) = self.width {
            my_size += ::protobuf::rt::int32_size(4, v);
        }
        if let Some(v) = self.rotation {
            my_size += 1 + 4;
        }
        if let Some(v) = self.rect_id {
            my_size += ::protobuf::rt::int64_size(6, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x_center {
            os.write_int32(1, v)?;
        }
        if let Some(v) = self.y_center {
            os.write_int32(2, v)?;
        }
        if let Some(v) = self.height {
            os.write_int32(3, v)?;
        }
        if let Some(v) = self.width {
            os.write_int32(4, v)?;
        }
        if let Some(v) = self.rotation {
            os.write_float(5, v)?;
        }
        if let Some(v) = self.rect_id {
            os.write_int64(6, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> Rect {
        Rect::new()
    }

    fn clear(&mut self) {
        self.x_center = ::std::option::Option::None;
        self.y_center = ::std::option::Option::None;
        self.height = ::std::option::Option::None;
        self.width = ::std::option::Option::None;
        self.rotation = ::std::option::Option::None;
        self.rect_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static Rect {
        static instance: Rect = Rect {
            x_center: ::std::option::Option::None,
            y_center: ::std::option::Option::None,
            height: ::std::option::Option::None,
            width: ::std::option::Option::None,
            rotation: ::std::option::Option::None,
            rect_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for Rect {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("Rect").unwrap()).clone()
    }
}

impl ::std::fmt::Display for Rect {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Rect {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:mediapipe.NormalizedRect)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct NormalizedRect {
    // message fields
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.x_center)
    pub x_center: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.y_center)
    pub y_center: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.height)
    pub height: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.width)
    pub width: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.rotation)
    pub rotation: ::std::option::Option<f32>,
    // @@protoc_insertion_point(field:mediapipe.NormalizedRect.rect_id)
    pub rect_id: ::std::option::Option<i64>,
    // special fields
    // @@protoc_insertion_point(special_field:mediapipe.NormalizedRect.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a NormalizedRect {
    fn default() -> &'a NormalizedRect {
        <NormalizedRect as ::protobuf::Message>::default_instance()
    }
}

impl NormalizedRect {
    pub fn new() -> NormalizedRect {
        ::std::default::Default::default()
    }

    // required float x_center = 1;

    pub fn x_center(&self) -> f32 {
        self.x_center.unwrap_or(0.)
    }

    pub fn clear_x_center(&mut self) {
        self.x_center = ::std::option::Option::None;
    }

    pub fn has_x_center(&self) -> bool {
        self.x_center.is_some()
    }

    // Param is passed by value, moved
    pub fn set_x_center(&mut self, v: f32) {
        self.x_center = ::std::option::Option::Some(v);
    }

    // required float y_center = 2;

    pub fn y_center(&self) -> f32 {
        self.y_center.unwrap_or(0.)
    }

    pub fn clear_y_center(&mut self) {
        self.y_center = ::std::option::Option::None;
    }

    pub fn has_y_center(&self) -> bool {
        self.y_center.is_some()
    }

    // Param is passed by value, moved
    pub fn set_y_center(&mut self, v: f32) {
        self.y_center = ::std::option::Option::Some(v);
    }

    // required float height = 3;

    pub fn height(&self) -> f32 {
        self.height.unwrap_or(0.)
    }

    pub fn clear_height(&mut self) {
        self.height = ::std::option::Option::None;
    }

    pub fn has_height(&self) -> bool {
        self.height.is_some()
    }

    // Param is passed by value, moved
    pub fn set_height(&mut self, v: f32) {
        self.height = ::std::option::Option::Some(v);
    }

    // required float width = 4;

    pub fn width(&self) -> f32 {
        self.width.unwrap_or(0.)
    }

    pub fn clear_width(&mut self) {
        self.width = ::std::option::Option::None;
    }

    pub fn has_width(&self) -> bool {
        self.width.is_some()
    }

    // Param is passed by value, moved
    pub fn set_width(&mut self, v: f32) {
        self.width = ::std::option::Option::Some(v);
    }

    // optional float rotation = 5;

    pub fn rotation(&self) -> f32 {
        self.rotation.unwrap_or(0.0f32)
    }

    pub fn clear_rotation(&mut self) {
        self.rotation = ::std::option::Option::None;
    }

    pub fn has_rotation(&self) -> bool {
        self.rotation.is_some()
    }

    // Param is passed by value, moved
    pub fn set_rotation(&mut self, v: f32) {
        self.rotation = ::std::option::Option::Some(v);
    }

    // optional int64 rect_id = 6;

    pub fn rect_id(&self) -> i64 {
        self.rect_id.unwrap_or(0)
    }

    pub fn clear_rect_id(&mut self) {
        self.rect_id = ::std::option::Option::None;
    }

    pub fn has_rect_id(&self) -> bool {
        self.rect_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_rect_id(&mut self, v: i64) {
        self.rect_id = ::std::option::Option::Some(v);
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(6);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "x_center",
            |m: &NormalizedRect| { &m.x_center },
            |m: &mut NormalizedRect| { &mut m.x_center },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "y_center",
            |m: &NormalizedRect| { &m.y_center },
            |m: &mut NormalizedRect| { &mut m.y_center },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "height",
            |m: &NormalizedRect| { &m.height },
            |m: &mut NormalizedRect| { &mut m.height },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "width",
            |m: &NormalizedRect| { &m.width },
            |m: &mut NormalizedRect| { &mut m.width },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "rotation",
            |m: &NormalizedRect| { &m.rotation },
            |m: &mut NormalizedRect| { &mut m.rotation },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "rect_id",
            |m: &NormalizedRect| { &m.rect_id },
            |m: &mut NormalizedRect| { &mut m.rect_id },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<NormalizedRect>(
            "NormalizedRect",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for NormalizedRect {
    const NAME: &'static str = "NormalizedRect";

    fn is_initialized(&self) -> bool {
        if self.x_center.is_none() {
            return false;
        }
        if self.y_center.is_none() {
            return false;
        }
        if self.height.is_none() {
            return false;
        }
        if self.width.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                13 => {
                    self.x_center = ::std::option::Option::Some(is.read_float()?);
                },
                21 => {
                    self.y_center = ::std::option::Option::Some(is.read_float()?);
                },
                29 => {
                    self.height = ::std::option::Option::Some(is.read_float()?);
                },
                37 => {
                    self.width = ::std::option::Option::Some(is.read_float()?);
                },
                45 => {
                    self.rotation = ::std::option::Option::Some(is.read_float()?);
                },
                48 => {
                    self.rect_id = ::std::option::Option::Some(is.read_int64()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.x_center {
            my_size += 1 + 4;
        }
        if let Some(v) = self.y_center {
            my_size += 1 + 4;
        }
        if let Some(v) = self.height {
            my_size += 1 + 4;
        }
        if let Some(v) = self.width {
            my_size += 1 + 4;
        }
        if let Some(v) = self.rotation {
            my_size += 1 + 4;
        }
        if let Some(v) = self.rect_id {
            my_size += ::protobuf::rt::int64_size(6, v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.x_center {
            os.write_float(1, v)?;
        }
        if let Some(v) = self.y_center {
            os.write_float(2, v)?;
        }
        if let Some(v) = self.height {
            os.write_float(3, v)?;
        }
        if let Some(v) = self.width {
            os.write_float(4, v)?;
        }
        if let Some(v) = self.rotation {
            os.write_float(5, v)?;
        }
        if let Some(v) = self.rect_id {
            os.write_int64(6, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> NormalizedRect {
        NormalizedRect::new()
    }

    fn clear(&mut self) {
        self.x_center = ::std::option::Option::None;
        self.y_center = ::std::option::Option::None;
        self.height = ::std::option::Option::None;
        self.width = ::std::option::Option::None;
        self.rotation = ::std::option::Option::None;
        self.rect_id = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static NormalizedRect {
        static instance: NormalizedRect = NormalizedRect {
            x_center: ::std::option::Option::None,
            y_center: ::std::option::Option::None,
            height: ::std::option::Option::None,
            width: ::std::option::Option::None,
            rotation: ::std::option::Option::None,
            rect_id: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for NormalizedRect {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("NormalizedRect").unwrap()).clone()
    }
}

impl ::std::fmt::Display for NormalizedRect {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NormalizedRect {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n&mediapipe/framework/formats/rect.proto\x12\tmediapipe\"\xa2\x01\n\x04\
    Rect\x12\x19\n\x08x_center\x18\x01\x20\x02(\x05R\x07xCenter\x12\x19\n\
    \x08y_center\x18\x02\x20\x02(\x05R\x07yCenter\x12\x16\n\x06height\x18\
    \x03\x20\x02(\x05R\x06height\x12\x14\n\x05width\x18\x04\x20\x02(\x05R\
    \x05width\x12\x1d\n\x08rotation\x18\x05\x20\x01(\x02:\x010R\x08rotation\
    \x12\x17\n\x07rect_id\x18\x06\x20\x01(\x03R\x06rectId\"\xac\x01\n\x0eNor\
    malizedRect\x12\x19\n\x08x_center\x18\x01\x20\x02(\x02R\x07xCenter\x12\
    \x19\n\x08y_center\x18\x02\x20\x02(\x02R\x07yCenter\x12\x16\n\x06height\
    \x18\x03\x20\x02(\x02R\x06height\x12\x14\n\x05width\x18\x04\x20\x02(\x02\
    R\x05width\x12\x1d\n\x08rotation\x18\x05\x20\x01(\x02:\x010R\x08rotation\
    \x12\x17\n\x07rect_id\x18\x06\x20\x01(\x03R\x06rectIdB/\n\"com.google.me\
    diapipe.formats.protoB\tRectProto\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(2);
            messages.push(Rect::generated_message_descriptor_data());
            messages.push(NormalizedRect::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
