#!/usr/bin/env python3
"""
MediaPipe Call Graph Visualizer

Creates visual representations of the MediaPipe hand inference pipeline
to show the complete C++ call graph flow.
"""

import json
from pathlib import Path
from typing import Dict, List, Set
import re

class CallGraphVisualizer:
    def __init__(self, analysis_file: Path):
        """Initialize with analysis results."""
        with open(analysis_file, 'r') as f:
            self.analysis = json.load(f)
    
    def generate_graphviz_dot(self, output_file: Path):
        """Generate a Graphviz DOT file for the call graph."""
        with open(output_file, 'w') as f:
            f.write("digraph MediaPipeHandInference {\n")
            f.write("  rankdir=LR;\n")
            f.write("  node [shape=box, style=filled];\n\n")
            
            # Color code different types of components
            f.write("  // Color scheme:\n")
            f.write("  // Blue: Core hand tracking calculators\n") 
            f.write("  // Green: Palm detection calculators\n")
            f.write("  // Orange: Landmark processing calculators\n")
            f.write("  // Yellow: Utility calculators\n")
            f.write("  // Red: Model loading calculators\n\n")
            
            # Add nodes with colors
            for name, component in self.analysis['components'].items():
                color = self._get_node_color(name)
                f.write(f'  "{name}" [fillcolor="{color}"];\n')
            
            f.write("\n  // Dependencies and relationships\n")
            
            # Add edges based on common patterns in MediaPipe
            self._add_pipeline_edges(f)
            
            f.write("}\n")
        
        print(f"Graphviz DOT file written to {output_file}")
    
    def _get_node_color(self, name: str) -> str:
        """Get color for a node based on its purpose."""
        name_lower = name.lower()
        
        if 'palm' in name_lower or 'detection' in name_lower:
            return "lightgreen"
        elif 'landmark' in name_lower:
            return "lightorange"
        elif 'model' in name_lower or 'loader' in name_lower:
            return "lightcoral"
        elif any(word in name_lower for word in ['hand', 'tracking']):
            return "lightblue"
        else:
            return "lightyellow"
    
    def _add_pipeline_edges(self, f):
        """Add edges showing the pipeline flow."""
        # Main pipeline flow for hand landmark tracking
        main_flow = [
            ("ImagePropertiesCalculator", "PalmDetectionCpu"),
            ("PalmDetectionCpu", "ClipDetectionVectorSizeCalculator"),
            ("ClipDetectionVectorSizeCalculator", "PalmDetectionDetectionToRoi"),
            ("PalmDetectionDetectionToRoi", "HandLandmarkCpu"),
            ("HandLandmarkCpu", "HandLandmarksToRectCalculator"),
            ("HandLandmarksToRectCalculator", "HandLandmarkLandmarksToRoi")
        ]
        
        for src, dst in main_flow:
            if src in self.analysis['components'] and dst in self.analysis['components']:
                f.write(f'  "{src}" -> "{dst}";\n')
    
    def generate_mermaid_diagram(self, output_file: Path):
        """Generate a Mermaid diagram for web viewing."""
        with open(output_file, 'w') as f:
            f.write("# MediaPipe Hand Inference Pipeline Diagram\n\n")
            f.write("**What this document contains:**\n")
            f.write("This document provides a Mermaid flowchart diagram of the MediaPipe hand inference pipeline, ")
            f.write("showing the key calculators and their relationships in a visual format suitable for ")
            f.write("web-based rendering and documentation.\n\n")
            f.write("**Generated by:** `call_graph_visualizer.py`\n\n")
            f.write("---\n\n")
            f.write("```mermaid\n")
            f.write("graph TD\n")
            
            # Add core pipeline nodes
            core_calculators = [
                "ImagePropertiesCalculator",
                "PalmDetectionCpu", 
                "PalmDetectionModelLoader",
                "HandLandmarkCpu",
                "HandLandmarkModelLoader",
                "HandLandmarksToRectCalculator"
            ]
            
            for calc in core_calculators:
                if calc in self.analysis['components']:
                    f.write(f"  {calc}[{calc}]\n")
            
            # Add flow connections
            f.write("  ImagePropertiesCalculator --> PalmDetectionCpu\n")
            f.write("  PalmDetectionModelLoader --> PalmDetectionCpu\n")
            f.write("  PalmDetectionCpu --> HandLandmarkCpu\n")
            f.write("  HandLandmarkModelLoader --> HandLandmarkCpu\n")
            f.write("  HandLandmarkCpu --> HandLandmarksToRectCalculator\n")
            
            f.write("```\n")
        
        print(f"Mermaid diagram written to {output_file}")
    
    def generate_execution_summary(self, output_file: Path):
        """Generate a text summary of the execution flow."""
        with open(output_file, 'w') as f:
            f.write("# MediaPipe Hand Inference C++ Execution Flow Summary\n\n")
            f.write("**What this document contains:**\n")
            f.write("This document provides a high-level summary of MediaPipe's hand inference pipeline execution flow, ")
            f.write("categorizing components by function (Palm Detection, Hand Landmark Detection, etc.) and listing ")
            f.write("the key C++ implementation files involved in each category. It serves as an executive summary ")
            f.write("for understanding the overall pipeline structure.\n\n")
            f.write("**Generated by:** `call_graph_visualizer.py`\n\n")
            f.write("---\n\n")
            f.write("## Key Pipeline Components\n\n")
            
            # Categorize components
            categories = {
                'Palm Detection': [],
                'Hand Landmark Detection': [],
                'Model Loading': [],
                'Coordinate Transformation': [],
                'Utility': []
            }
            
            for name, component in self.analysis['components'].items():
                name_lower = name.lower()
                
                if 'palm' in name_lower or 'detection' in name_lower:
                    categories['Palm Detection'].append(name)
                elif 'landmark' in name_lower:
                    categories['Hand Landmark Detection'].append(name) 
                elif 'model' in name_lower or 'loader' in name_lower:
                    categories['Model Loading'].append(name)
                elif any(word in name_lower for word in ['transform', 'rect', 'roi', 'projection']):
                    categories['Coordinate Transformation'].append(name)
                else:
                    categories['Utility'].append(name)
            
            for category, components in categories.items():
                if components:
                    f.write(f"### {category}\n\n")
                    for comp in sorted(components):
                        component_data = self.analysis['components'][comp]
                        impl_files = len(component_data['implementation_files'])
                        class_name = component_data['class_name']
                        f.write(f"- **{comp}**")
                        if class_name:
                            f.write(f" (`{class_name}`)")
                        if impl_files > 0:
                            f.write(f" - {impl_files} C++ files")
                        f.write("\n")
                    f.write("\n")
            
            # Execution flow description
            f.write("## Execution Flow Description\n\n")
            f.write("The MediaPipe hand inference pipeline follows this general flow:\n\n")
            f.write("1. **Image Input Processing** - Input image is processed to extract properties\n")
            f.write("2. **Palm Detection** - Detect palms in the image using ML model\n")
            f.write("3. **ROI Extraction** - Convert palm detections to regions of interest\n")
            f.write("4. **Hand Landmark Detection** - Run landmark detection on hand ROIs\n")
            f.write("5. **Coordinate Transformation** - Transform landmarks between coordinate systems\n")
            f.write("6. **Tracking Preparation** - Generate ROIs for next frame tracking\n\n")
            
            # C++ files summary
            f.write("## Complete C++ Implementation Files\n\n")
            all_files = set()
            for component in self.analysis['components'].values():
                all_files.update(component['implementation_files'])
            
            f.write(f"**Total C++ files involved: {len(all_files)}**\n\n")
            
            # Group files by directory
            file_groups = {}
            for file_path in sorted(all_files):
                if file_path:
                    path_obj = Path(file_path)
                    # Get the calculator directory (e.g., calculators/core, calculators/util)
                    parts = path_obj.parts
                    if 'calculators' in parts:
                        calc_idx = parts.index('calculators')
                        if calc_idx + 1 < len(parts):
                            group = f"calculators/{parts[calc_idx + 1]}"
                        else:
                            group = "calculators"
                    else:
                        group = "other"
                    
                    if group not in file_groups:
                        file_groups[group] = []
                    file_groups[group].append(file_path)
            
            for group, files in sorted(file_groups.items()):
                f.write(f"### {group}\n\n")
                for file_path in sorted(files):
                    f.write(f"- `{Path(file_path).name}`\n")
                f.write("\n")
        
        print(f"Execution summary written to {output_file}")

def main():
    """Generate visualizations from the analysis results."""
    analysis_file = Path(__file__).parent / "output" / "all_calculators_and_cpp_sources.json"
    
    if not analysis_file.exists():
        print(f"Analysis file not found: {analysis_file}")
        return
    
    visualizer = CallGraphVisualizer(analysis_file)
    output_dir = Path(__file__).parent / "output"
    output_dir.mkdir(exist_ok=True)
    
    # Generate different visualizations
    visualizer.generate_graphviz_dot(output_dir / "hand_pipeline_graph.dot")
    visualizer.generate_mermaid_diagram(output_dir / "pipeline_visual_flowchart.md")
    visualizer.generate_execution_summary(output_dir / "calculator_functional_categories.md")
    
    print("\n=== Visualization Generation Complete ===")
    print(f"Generated files in: {output_dir}")
    print("- hand_pipeline_graph.dot (Graphviz)")
    print("- pipeline_visual_flowchart.md (Mermaid)")
    print("- calculator_functional_categories.md (Text summary)")

if __name__ == "__main__":
    main()