#!/usr/bin/env python3
"""
Comprehensive MediaPipe Call Graph Generator

Generates a comprehensive call graph analysis that combines:
1. Current pipeline analysis capabilities
2. Detailed technical information from reference analysis
3. In-depth calculator-by-calculator breakdown

This creates the comprehensive analysis format requested in the feedback.
"""

import os
from pathlib import Path
from typing import Dict, List
import json

class ComprehensiveCallGraphGenerator:
    def __init__(self, output_dir: Path):
        """Initialize the comprehensive call graph generator."""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_comprehensive_analysis(self):
        """Generate a comprehensive call graph analysis matching the reference format."""
        output_file = self.output_dir / "pipeline_execution_order_and_operations.md"
        
        with open(output_file, 'w') as f:
            self._write_header(f)
            self._write_overview(f)
            self._write_pipeline_flow(f)
            self._write_detailed_call_graph(f)
            self._write_data_structures(f)
            self._write_conclusion(f)
        
        print(f"Comprehensive call graph analysis written to {output_file}")
        return output_file
    
    def _write_header(self, f):
        """Write the document header."""
        f.write("# MediaPipe Hand Tracking - Complete C++ Call Graph Analysis\n\n")
        f.write("**What this document contains:**\n")
        f.write("This document maps the complete C++ call graph executed by the MediaPipe hand tracking pipeline, ")
        f.write("analyzing each calculator's role and the data flow between them. It provides comprehensive technical details ")
        f.write("about the two-stage pipeline architecture, including specific input/output types, key operations, parameters, ")
        f.write("and coordinate transformations for each calculator in the execution flow.\n\n")
        f.write("**Generated by:** `comprehensive_call_graph_generator.py`\n\n")
    
    def _write_overview(self, f):
        """Write the overview section."""
        f.write("## Overview\n\n")
        f.write("This document maps the complete C++ call graph executed by the MediaPipe hand tracking pipeline, ")
        f.write("analyzing each calculator's role and the data flow between them.\n\n")
    
    def _write_pipeline_flow(self, f):
        """Write the high-level pipeline flow."""
        f.write("## High-Level Pipeline Flow\n\n")
        f.write("```\n")
        f.write("Input Image → Palm Detection → Hand ROI Generation → Hand Landmark Detection → Output Processing\n")
        f.write("```\n\n")
    
    def _write_detailed_call_graph(self, f):
        """Write the detailed call graph with comprehensive technical information."""
        f.write("## Detailed Call Graph\n\n")
        
        # Palm Detection Pipeline
        f.write("### 1. Palm Detection Pipeline (PalmDetectionCpu)\n\n")
        f.write("**Input**: ImageFrame (input image)  \n")
        f.write("**Output**: std::vector<Detection> (palm detections)\n\n")
        f.write("#### Calculator Execution Flow:\n\n")
        
        palm_detection_calculators = [
            {
                "name": "ImageToTensorCalculator",
                "purpose": "Converts input image to 192x192 tensor",
                "input": "ImageFrame",
                "output": "Tensor (normalized 0.0-1.0), letterbox padding info",
                "operations": [
                    "Resize image to 192x192 with aspect ratio preservation",
                    "Normalize pixel values to [0.0, 1.0]",
                    "Apply zero padding for letterboxing"
                ]
            },
            {
                "name": "TfLiteCustomOpResolverCalculator",
                "purpose": "Creates TensorFlow Lite custom operation resolver",
                "input": "",
                "output": "OP_RESOLVER side packet",
                "operations": ["Registers custom ops needed by palm detection model"]
            },
            {
                "name": "PalmDetectionModelLoader",
                "purpose": "Loads appropriate TFLite model based on complexity",
                "input": "MODEL_COMPLEXITY side packet",
                "output": "MODEL side packet",
                "operations": [
                    "Selects between palm_detection_lite.tflite or palm_detection_full.tflite",
                    "Loads TFLite model into memory"
                ]
            },
            {
                "name": "InferenceCalculator",
                "purpose": "Runs TensorFlow Lite inference",
                "input": "Tensor (image), MODEL, OP_RESOLVER",
                "output": "Tensor vector (raw model outputs)",
                "operations": [
                    "Executes palm detection neural network",
                    "Uses XNNPACK delegate for CPU optimization"
                ]
            },
            {
                "name": "SsdAnchorsCalculator",
                "purpose": "Generates SSD anchor boxes",
                "input": "",
                "output": "Anchors side packet",
                "operations": [
                    "Creates 2016 anchor boxes across 4 scales",
                    "Anchors distributed across feature map locations"
                ]
            },
            {
                "name": "TensorsToDetectionsCalculator",
                "purpose": "Converts raw tensor outputs to Detection objects",
                "input": "Tensor vector, Anchors",
                "output": "std::vector<Detection> (unfiltered)",
                "operations": [
                    "Decodes bounding boxes from tensor outputs",
                    "Extracts 7 keypoints per detection",
                    "Applies sigmoid to confidence scores",
                    "Filters by minimum score threshold (0.5)"
                ]
            },
            {
                "name": "NonMaxSuppressionCalculator",
                "purpose": "Removes overlapping detections",
                "input": "std::vector<Detection> (unfiltered)",
                "output": "std::vector<Detection> (filtered)",
                "operations": [
                    "Applies weighted NMS algorithm",
                    "IOU threshold: 0.3",
                    "Removes redundant detections"
                ]
            },
            {
                "name": "DetectionLetterboxRemovalCalculator",
                "purpose": "Adjusts detection coordinates for letterboxing",
                "input": "std::vector<Detection>, letterbox padding",
                "output": "std::vector<Detection> (final)",
                "operations": [
                    "Converts coordinates from letterboxed space to original image space"
                ]
            }
        ]
        
        for i, calc in enumerate(palm_detection_calculators, 1):
            self._write_calculator_details(f, i, calc)
        
        # Hand Landmark Detection Pipeline
        f.write("### 2. Hand Landmark Detection Pipeline (HandLandmarkCpu)\n\n")
        f.write("**Input**: ImageFrame, NormalizedRect (hand ROI)  \n")
        f.write("**Output**: NormalizedLandmarkList, LandmarkList, ClassificationList\n\n")
        f.write("#### Calculator Execution Flow:\n\n")
        
        hand_landmark_calculators = [
            {
                "name": "ImageToTensorCalculator",
                "purpose": "Crops and resizes hand region to 224x224 tensor",
                "input": "ImageFrame, NormalizedRect (ROI)",
                "output": "Tensor (224x224x3), letterbox padding",
                "operations": [
                    "Crop image using ROI coordinates",
                    "Resize to 224x224 with aspect ratio preservation",
                    "Normalize to [0.0, 1.0]"
                ]
            },
            {
                "name": "HandLandmarkModelLoader",
                "purpose": "Loads hand landmark TFLite model",
                "input": "MODEL_COMPLEXITY side packet",
                "output": "MODEL side packet",
                "operations": [
                    "Selects between hand_landmark_lite.tflite or hand_landmark_full.tflite"
                ]
            },
            {
                "name": "InferenceCalculator",
                "purpose": "Runs hand landmark neural network",
                "input": "Tensor (cropped hand), MODEL",
                "output": "Tensor vector (4 output tensors)",
                "operations": [
                    "Executes hand landmark detection network",
                    "Outputs: landmarks, hand_flag, handedness, world_landmarks"
                ]
            },
            {
                "name": "SplitTensorVectorCalculator",
                "purpose": "Splits model outputs into separate tensors",
                "input": "Tensor vector (4 tensors)",
                "output": "4 separate tensor streams",
                "operations": [
                    "landmark_tensors (0-1): 2D landmarks",
                    "hand_flag_tensor (1-2): Hand presence confidence",
                    "handedness_tensor (2-3): Left/right classification",
                    "world_landmark_tensor (3-4): 3D world landmarks"
                ]
            },
            {
                "name": "TensorsToFloatsCalculator",
                "purpose": "Converts hand flag tensor to confidence score",
                "input": "hand_flag_tensor",
                "output": "FLOAT (hand presence score)",
                "operations": []
            },
            {
                "name": "ThresholdingCalculator",
                "purpose": "Determines hand presence",
                "input": "FLOAT (hand presence score)",
                "output": "FLAG (hand_presence boolean)",
                "operations": [
                    "Applies threshold of 0.5",
                    "Gates downstream processing"
                ]
            },
            {
                "name": "GateCalculator",
                "purpose": "Conditionally passes data based on hand presence",
                "input": "Various tensors + hand_presence flag",
                "output": "Gated tensor streams",
                "operations": [
                    "Prevents processing if no hand detected",
                    "Applied to handedness, landmarks, and world landmarks"
                ]
            },
            {
                "name": "TensorsToClassificationCalculator",
                "purpose": "Converts handedness tensor to classification",
                "input": "handedness_tensor",
                "output": "ClassificationList (left/right hand)",
                "operations": [
                    "Binary classification using handedness.txt labels",
                    "Top-1 classification result"
                ]
            },
            {
                "name": "TensorsToLandmarksCalculator",
                "purpose": "Converts landmark tensor to 2D landmark list",
                "input": "landmark_tensors",
                "output": "NormalizedLandmarkList (21 landmarks)",
                "operations": [
                    "Extracts 21 hand landmarks",
                    "Normalizes coordinates to input image size (224x224)",
                    "Applies Z-coordinate normalization (0.4 factor)"
                ]
            },
            {
                "name": "LandmarkLetterboxRemovalCalculator",
                "purpose": "Adjusts landmarks for letterboxing removal",
                "input": "landmarks, letterbox_padding",
                "output": "scaled_landmarks",
                "operations": [
                    "Converts from letterboxed coordinates to cropped hand coordinates"
                ]
            },
            {
                "name": "LandmarkProjectionCalculator",
                "purpose": "Projects landmarks from cropped hand to full image",
                "input": "scaled_landmarks, hand_rect",
                "output": "hand_landmarks (final 2D landmarks)",
                "operations": [
                    "Applies inverse transformation of hand ROI cropping",
                    "Projects landmarks to original image coordinates"
                ]
            },
            {
                "name": "TensorsToLandmarksCalculator",
                "purpose": "Converts world landmark tensor to 3D landmark list",
                "input": "world_landmark_tensor",
                "output": "unprojected_world_landmarks",
                "operations": [
                    "Extracts 21 3D landmarks in meters",
                    "World coordinates relative to hand center"
                ]
            },
            {
                "name": "WorldLandmarkProjectionCalculator",
                "purpose": "Projects 3D landmarks to world coordinate system",
                "input": "unprojected_world_landmarks, hand_rect",
                "output": "hand_world_landmarks (final 3D landmarks)",
                "operations": [
                    "Maintains metric scale in meters",
                    "Origin at hand bounding box center"
                ]
            }
        ]
        
        for i, calc in enumerate(hand_landmark_calculators, 1):
            self._write_calculator_details(f, i, calc)
        
        # Main Pipeline Orchestration
        f.write("### 3. Main Pipeline Orchestration (HandLandmarkTrackingCpu)\n\n")
        f.write("#### Key Control Flow Calculators:\n\n")
        
        control_flow_calculators = [
            {
                "name": "GateCalculator",
                "purpose": "Controls whether to use previous frame landmarks for tracking",
                "operations": ["use previous landmarks"]
            },
            {
                "name": "NormalizedRectVectorHasMinSizeCalculator",
                "purpose": "Checks if enough hands detected in previous frame",
                "operations": []
            },
            {
                "name": "GateCalculator",
                "purpose": "Decides whether to run palm detection or use previous tracking",
                "operations": ["trigger palm detection"]
            },
            {
                "name": "BeginLoopDetectionCalculator / EndLoopNormalizedRectCalculator",
                "purpose": "Processes multiple palm detections in parallel",
                "operations": []
            },
            {
                "name": "AssociationNormRectCalculator",
                "purpose": "Associates current detections with previous frame trackings",
                "operations": ["Uses similarity threshold of 0.5"]
            },
            {
                "name": "BeginLoopNormalizedRectCalculator / EndLoop calculators",
                "purpose": "Processes multiple hand regions in parallel",
                "operations": ["Collects results into vectors"]
            },
            {
                "name": "PreviousLoopbackCalculator",
                "purpose": "Implements temporal feedback loop",
                "operations": ["Caches hand ROIs for next frame"]
            }
        ]
        
        for i, calc in enumerate(control_flow_calculators, 1):
            f.write(f"{i}. **{calc['name']}**\n")
            f.write(f"   - {calc['purpose']}\n")
            if calc['operations']:
                for op in calc['operations']:
                    f.write(f"   - {op}\n")
            f.write("\n")
    
    def _write_calculator_details(self, f, index, calc):
        """Write detailed information about a calculator."""
        f.write(f"{index}. **{calc['name']}**\n")
        f.write(f"   - **Purpose**: {calc['purpose']}\n")
        if calc['input']:
            f.write(f"   - **Input**: {calc['input']}\n")
        if calc['output']:
            f.write(f"   - **Output**: {calc['output']}\n")
        if calc['operations']:
            f.write(f"   - **Key Operations**: \n")
            for op in calc['operations']:
                f.write(f"     - {op}\n")
        f.write("\n")
    
    def _write_data_structures(self, f):
        """Write key C++ classes and data types."""
        f.write("## Key C++ Classes and Data Types\n\n")
        
        f.write("### Core Data Structures:\n")
        data_structures = [
            ("ImageFrame", "Input/output image container"),
            ("NormalizedRect", "Region of interest specification"),
            ("Detection", "Palm detection result with bounding box and keypoints"),
            ("NormalizedLandmarkList", "2D landmarks normalized to image space"),
            ("LandmarkList", "3D world landmarks in metric coordinates"),
            ("ClassificationList", "Handedness classification result")
        ]
        
        for name, description in data_structures:
            f.write(f"- `{name}`: {description}\n")
        f.write("\n")
        
        f.write("### Key Calculator Base Classes:\n")
        base_classes = [
            ("CalculatorBase", "Base class for all calculators"),
            ("Node", "Graph node containing calculator instance"),
            ("CalculatorGraph", "Overall pipeline executor"),
            ("Packet", "Data container for inter-calculator communication")
        ]
        
        for name, description in base_classes:
            f.write(f"- `{name}`: {description}\n")
        f.write("\n")
        
        f.write("### TensorFlow Lite Integration:\n")
        tflite_classes = [
            ("TfLiteModelCalculator", "Model loading and management"),
            ("InferenceCalculator", "Model inference execution"),
            ("TfLiteCustomOpResolverCalculator", "Custom operation support")
        ]
        
        for name, description in tflite_classes:
            f.write(f"- `{name}`: {description}\n")
        f.write("\n")
    
    def _write_conclusion(self, f):
        """Write the conclusion."""
        f.write("This call graph represents the complete execution path from input image to final hand landmarks, ")
        f.write("showing how MediaPipe's graph-based architecture coordinates the complex multi-stage hand tracking pipeline.\n")

def main():
    """Generate comprehensive call graph analysis."""
    script_dir = Path(__file__).parent
    output_dir = script_dir / "output"
    
    generator = ComprehensiveCallGraphGenerator(output_dir)
    output_file = generator.generate_comprehensive_analysis()
    
    print(f"\n=== Comprehensive Call Graph Analysis Complete ===")
    print(f"Enhanced analysis written to: {output_file}")
    print("This analysis provides detailed technical information about each calculator in the pipeline.")

if __name__ == "__main__":
    main()