"""
Generates a markdown report of all side packets produced by nodes in a MediaPipe pipeline.
Reads the verbose JSON output file generated by pipeline_parser.py, extracts side packets and their producing nodes,
and writes the report to output/side-packets.md.
"""
import json
import os
from typing import Dict, Any, List, Tuple, DefaultDict
from collections import defaultdict

# Path to the input verbose JSON file generated by pipeline_parser.py
INPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "output", "json", "pipeline.verbose.json")
# Path to the output markdown file
OUTPUT_MD_PATH = os.path.join(os.path.dirname(__file__), "output", "side-packets.md")

SIDE_PACKET_KEYS = ["output_side_packets", "input_side_packets", "side_packets"]
CONSUMED_PACKET_KEYS = ["input_side_packets", "side_packets"]

# Helper to recursively collect all nodes

def collect_all_nodes(node: Dict[str, Any], parent_name: str = None) -> List[Dict[str, Any]]:
    nodes = []
    node_name = node.get("name", parent_name or "<unnamed node>")
    node_type = node.get("type", "<unknown type>")
    source = node.get("source", "")
    nodes.append({"name": node_name, "type": node_type, "source": source, "raw": node})
    for child in node.get("nodes", []):
        nodes.extend(collect_all_nodes(child, node_name))
    return nodes

def extract_side_packet_relations(all_nodes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """
    For each produced side packet, find all consumers and build the report rows.
    """
    # Map: side_packet_name -> list of (consumer_name, consumer_source)
    consumed_by: DefaultDict[str, List[Tuple[str, str]]] = defaultdict(list)
    # First, build the consumer map
    for node in all_nodes:
        raw = node["raw"]
        node_name = node["name"]
        node_source = node["source"]
        for key in CONSUMED_PACKET_KEYS:
            for sp in raw.get(key, []):
                consumed_by[sp].append((node_name, node_source))
    # Now, for each produced side packet, build the report row
    report_rows = []
    for node in all_nodes:
        raw = node["raw"]
        node_name = node["name"]
        node_type = node["type"]
        node_source = node["source"]
        for key in SIDE_PACKET_KEYS:
            for sp in raw.get(key, []):
                consumers = consumed_by.get(sp, [])
                # Format consumers as hyperlinks, <br>-delimited
                if consumers:
                    consumers_md = "<br>".join([
                        f"[{cname}]({csource})" if csource else cname
                        for cname, csource in consumers
                    ])
                else:
                    consumers_md = ""
                report_rows.append({
                    "node": node_name,
                    "type": node_type,
                    "source": node_source,
                    "side_packet": sp,
                    "consumed_by": consumers_md
                })
    return report_rows

def generate_markdown(rows: List[Dict[str, str]]) -> str:
    """
    Generates markdown listing all side packets, their producing nodes, node type, and consumers (hyperlinked, <br>-delimited).
    """
    if not rows:
        raise Exception("could not read the input json analysis file, have you run pipeline_parser.py to make it available?")
    md = ["# Side Packets Report\n"]
    md.append("| Pipeline Producer Node | Node Type | Side Packet | Pipeline Consumer Node |")
    md.append("|------|-----------|-------------|-------------|")
    for entry in rows:
        node_link = f"[{entry['node']}]({entry['source']})" if entry['source'] else entry['node']
        md.append(f"| {node_link} | {entry['type']} | {entry['side_packet']} | {entry['consumed_by']} |")
    return "\n".join(md)

def main():
    if not os.path.exists(INPUT_JSON_PATH):
        print(f"Error: Input JSON file not found at {INPUT_JSON_PATH}")
        return
    with open(INPUT_JSON_PATH, "r") as f:
        json_data = json.load(f)
    all_nodes = collect_all_nodes(json_data)
    report_rows = extract_side_packet_relations(all_nodes)
    md = generate_markdown(report_rows)
    with open(OUTPUT_MD_PATH, "w") as f:
        f.write(md)
    print(f"Markdown report written to {OUTPUT_MD_PATH}")

if __name__ == "__main__":
    main()
