"""
Generates a markdown report of all side packets produced by nodes in a MediaPipe pipeline.
Reads the verbose JSON output file generated by pipeline_parser.py, extracts side packets and their producing nodes,
and writes the report to output/side-packets.md.
"""
import json
import os
from typing import Dict, Any, List, Tuple, DefaultDict
from collections import defaultdict

# Path to the input verbose JSON file generated by pipeline_parser.py
INPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "output", "json", "pipeline.verbose.json")
# Path to the output markdown file
OUTPUT_MD_PATH = os.path.join(os.path.dirname(__file__), "output", "side-packets.md")
SIDE_PACKET_OUTPUT_KEY = "output_side_packets"
SIDE_PACKET_INPUT_KEY = "input_side_packets"

# Helper to recursively collect all nodes

def collect_all_nodes(node: Dict[str, Any], parent_name: str = None) -> List[Dict[str, Any]]:
    nodes = []
    node_name = node.get("name", parent_name or "<unnamed node>")
    node_type = node.get("type", "<unknown type>")
    source = node.get("source", "")
    nodes.append({"name": node_name, "type": node_type, "source": source, "raw": node})
    for child in node.get("nodes", []):
        nodes.extend(collect_all_nodes(child, node_name))
    return nodes

def extract_side_packet_relations(all_nodes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """
    For each produced side packet (Tag:name), correlate all consumers that match by MediaPipe rules:
    - If consumer's input_side_packet is tag:name, match only if producer's output_side_packet is tag:name, or if producer's tag or name matches.
    - If consumer's input_side_packet is just name, match any producer with that name (regardless of tag).
    - If consumer's input_side_packet is just tag, match any producer with that tag (regardless of name).
    Deduplicate consumers per row.
    """
    produced_packets = []  # List of (node_name, node_type, node_source, tag, name, full_tag_name)
    for node in all_nodes:
        raw = node["raw"]
        node_name = node["name"]
        node_type = node["type"]
        node_source = node["source"]
        for sp in raw.get(SIDE_PACKET_OUTPUT_KEY, []):
            if ":" in sp:
                tag, name = sp.split(":", 1)
            else:
                tag, name = "", sp
            produced_packets.append((node_name, node_type, node_source, tag, name, sp))
    report_rows = []
    for prod_node, prod_type, prod_source, prod_tag, prod_name, prod_full in produced_packets:
        consumers_set = set()
        for node in all_nodes:
            raw = node["raw"]
            node_name = node["name"]
            node_type = node["type"]
            node_source = node["source"]
            for sp in raw.get(SIDE_PACKET_INPUT_KEY, []):
                if ":" in sp:
                    ctag, cname = sp.split(":", 1)
                    # Strict match: both tag and name must match
                    if (ctag == prod_tag and cname == prod_name) or (ctag == prod_tag and not prod_name) or (cname == prod_name and not prod_tag):
                        consumers_set.add((node_name, node_source))
                else:
                    # Only name or only tag present
                    if sp == prod_name or sp == prod_tag:
                        consumers_set.add((node_name, node_source))
        consumers_md = "<br>".join([
            f"[{cname}]({csource})" if csource else cname
            for cname, csource in sorted(consumers_set)
        ])
        report_rows.append({
            "producer": f"[{prod_node}]({prod_source})" if prod_source else prod_node,
            "type": prod_type,
            "side_packet": prod_full,
            "consumer": consumers_md
        })
    return report_rows

def generate_markdown(rows: List[Dict[str, str]]) -> str:
    """
    Generates markdown listing all produced Tag:name packets, their producer node, and all matching consumers (hyperlinked, <br>-delimited).
    """
    if rows is None:
        raise Exception("could not read the input json analysis file, have you run pipeline_parser.py to make it available?")
    md = ["# Side Packets Report\n"]
    md.append("| Producer Node | Type | Output Side Packet | Consumer Node(s) |")
    md.append("|--------------|------|-------------------|------------------|")
    for entry in rows:
        md.append(f"| {entry['producer']} | {entry['type']} | {entry['side_packet']} | {entry['consumer']} |")
    return "\n".join(md)

def main():
    if not os.path.exists(INPUT_JSON_PATH):
        print(f"Error: Input JSON file not found at {INPUT_JSON_PATH}")
        return
    with open(INPUT_JSON_PATH, "r") as f:
        json_data = json.load(f)
    all_nodes = collect_all_nodes(json_data)
    report_rows = extract_side_packet_relations(all_nodes)
    md = generate_markdown(report_rows)
    with open(OUTPUT_MD_PATH, "w") as f:
        f.write(md)
    print(f"Markdown report written to {OUTPUT_MD_PATH}")

if __name__ == "__main__":
    main()
