"""
Generates a markdown report of all side packets produced by nodes in a MediaPipe pipeline.
Reads the verbose JSON output file generated by pipeline_parser.py, extracts side packets and their producing nodes,
and writes the report to output/side-packets.md.
"""
import json
import os
from typing import Dict, Any, List, Tuple, DefaultDict
from collections import defaultdict

# Path to the input verbose JSON file generated by pipeline_parser.py
INPUT_JSON_PATH = os.path.join(os.path.dirname(__file__), "output", "json", "pipeline.verbose.json")
# Path to the output markdown file
OUTPUT_MD_PATH = os.path.join(os.path.dirname(__file__), "output", "side-packets.md")

SIDE_PACKET_KEYS = ["output_side_packets", "input_side_packets", "side_packets"]
CONSUMED_PACKET_KEYS = ["input_side_packets", "side_packets"]

# Helper to recursively collect all nodes

def collect_all_nodes(node: Dict[str, Any], parent_name: str = None) -> List[Dict[str, Any]]:
    nodes = []
    node_name = node.get("name", parent_name or "<unnamed node>")
    node_type = node.get("type", "<unknown type>")
    source = node.get("source", "")
    nodes.append({"name": node_name, "type": node_type, "source": source, "raw": node})
    for child in node.get("nodes", []):
        nodes.extend(collect_all_nodes(child, node_name))
    return nodes

def extract_side_packet_relations(all_nodes: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    """
    For each produced side packet, find all consumers and build the report rows.
    Implements MediaPipe packet resolution rules:
    - A consumer matches a side packet if:
      * The full tag:name matches
      * The name (right side of a:b) matches, regardless of tag
      * The tag (left side of a:b) matches, regardless of name
      * The consumer references just the name, and any producer has that name
      * The consumer references just the tag, and any producer has that tag
    This logic is crucial for correct MediaPipe packet resolution and will match RESOURCE:model_resource to MODEL_RESOURCE:model_resource by name.
    """
    # Map: produced side_packet_name -> (producer_name, producer_source, node_type, tag, name)
    produced_packets = {}
    for node in all_nodes:
        raw = node["raw"]
        node_name = node["name"]
        node_source = node["source"]
        node_type = node["type"]
        for key in SIDE_PACKET_KEYS:
            for sp in raw.get(key, []):
                if ":" in sp:
                    tag, name = sp.split(":", 1)
                else:
                    tag, name = sp, sp
                produced_packets[sp] = (node_name, node_source, node_type, tag, name)
    # Map: produced side_packet_name -> list of (consumer_name, consumer_source)
    consumed_by = {sp: [] for sp in produced_packets}
    # --- MediaPipe packet resolution rules implemented below ---
    for node in all_nodes:
        raw = node["raw"]
        node_name = node["name"]
        node_source = node["source"]
        for key in CONSUMED_PACKET_KEYS:
            for consumer_ref in raw.get(key, []):
                if ":" in consumer_ref:
                    ctag, cname = consumer_ref.split(":", 1)
                else:
                    ctag, cname = consumer_ref, consumer_ref
                for produced_name, (pnode, psource, ptype, ptag, pname) in produced_packets.items():
                    # Prominent comment: MediaPipe packet resolution rules
                    # Match if:
                    # - Full tag:name matches
                    # - Name matches (regardless of tag)
                    # - Tag matches (regardless of name)
                    # - Consumer references just name, match any producer with that name
                    # - Consumer references just tag, match any producer with that tag
                    if (
                        consumer_ref == produced_name or
                        consumer_ref == pname or
                        consumer_ref == ptag or
                        (":" in consumer_ref and cname == pname) or
                        (":" in consumer_ref and ctag == ptag)
                    ):
                        consumed_by[produced_name].append((node_name, node_source))
    # Now, for each produced side packet, build the report row
    report_rows = []
    for sp, (node_name, node_source, node_type, tag, name) in produced_packets.items():
        consumers = consumed_by.get(sp, [])
        # Format consumers as hyperlinks, <br>-delimited
        if consumers:
            consumers_md = "<br>".join([
                f"[{cname}]({csource})" if csource else cname
                for cname, csource in consumers
            ])
        else:
            consumers_md = ""
        report_rows.append({
            "node": node_name,
            "type": node_type,
            "source": node_source,
            "side_packet": sp,
            "consumed_by": consumers_md
        })
    return report_rows

def generate_markdown(rows: List[Dict[str, str]]) -> str:
    """
    Generates markdown listing all side packets, their producing nodes, node type, and consumers (hyperlinked, <br>-delimited).
    """
    if not rows:
        raise Exception("could not read the input json analysis file, have you run pipeline_parser.py to make it available?")
    md = ["# Side Packets Report\n"]
    md.append("| Pipeline Producer Node | Type | Output Side Packet | Pipeline Consumer Node |")
    md.append("|------|-----------|-------------|-------------|")
    for entry in rows:
        node_link = f"[{entry['node']}]({entry['source']})" if entry['source'] else entry['node']
        md.append(f"| {node_link} | {entry['type']} | {entry['side_packet']} | {entry['consumed_by']} |")
    return "\n".join(md)

def main():
    if not os.path.exists(INPUT_JSON_PATH):
        print(f"Error: Input JSON file not found at {INPUT_JSON_PATH}")
        return
    with open(INPUT_JSON_PATH, "r") as f:
        json_data = json.load(f)
    all_nodes = collect_all_nodes(json_data)
    report_rows = extract_side_packet_relations(all_nodes)
    md = generate_markdown(report_rows)
    with open(OUTPUT_MD_PATH, "w") as f:
        f.write(md)
    print(f"Markdown report written to {OUTPUT_MD_PATH}")

if __name__ == "__main__":
    main()
