# MediaPipe graph to detect palms with TensorFlow Lite on CPU.

type: "PalmDetectionCpu"

# CPU image. (ImageFrame)
input_stream: "IMAGE:image"

# Detected palms. (std::vector<Detection>)
# NOTE: there will not be an output packet in the DETECTIONS stream for this
# particular timestamp if none of palms detected. However, the MediaPipe
# framework will internally inform the downstream calculators of the absence of
# this packet so that they don't wait for it unnecessarily.
output_stream: "DETECTIONS:detections"

# Transforms an image into a 128x128 tensor while keeping the aspect ratio, and
# therefore will result in letterboxing unless the input image was somehow rectangular,
# which an image taken from a webcam in our scenario is not.
node {
  calculator: "ImageToTensorCalculator"
  input_stream: "IMAGE:image"
  output_stream: "TENSORS:input_tensor"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
#  options: {
#    [mediapipe_v01013_based.ImageToTensorCalculatorOptions.ext] {
#      output_tensor_width: 192
#      output_tensor_height: 192
#      keep_aspect_ratio: true
#      output_tensor_float_range {
#        min: 0.0
#        max: 1.0
#      }
#      border_mode: BORDER_ZERO
#    }
#  }
}

# Sets the path to the desired palms detection model file. we can only remove this
# We can only remove this at the last mile of liberation ― where a full-blown transform
# of the InferenceCalculator into a stateful plain object is performed
node {
  calculator: "SwitchContainer"
  input_side_packet: "SELECT:model_complexity"
  output_side_packet: "PACKET:model_path"
  options: {
    [mediapipe_v01013_based.SwitchContainerOptions.ext] {
      contained_node: {
        calculator: "ConstantSidePacketCalculator"
        options: {
          [mediapipe_v01013_based.ConstantSidePacketCalculatorOptions.ext]: {
            packet {
              string_value: "mediapipe/modules/palm_detection/palm_detection_full.tflite"
            }
          }
        }
      }
    }
  }
}

# Runs the TensorFlow Lite SSD palm detection model
node {
  calculator: "InferenceCalculator"
  input_stream: "TENSORS:input_tensor"
  output_stream: "TENSORS:detection_tensors"
  input_side_packet: "MODEL_PATH:model_path"
  options: {
    [mediapipe_v01013_based.InferenceCalculatorOptions.ext] {
      delegate { xnnpack {} }
    }
  }
}

# Decodes the detection tensors generated by the SSD palms detection model into
# mediapipe Detection objects, while filtering the network's outputs by several
# criteria including finally applying Non-Maximum Suppression (NMS).
node {
  calculator: "TensorsToDetectionsCalculator"
  input_stream: "TENSORS:detection_tensors"
   output_stream: "DETECTIONS:filtered_detections"
}

# translates the detection coordinates to the original image coordinates,
# thus undoing the effect of the letterboxing which was necessary for using the neural network model:
#  Adjusts detection locations (already normalized to [0.f, 1.f]) on the letterboxed image (after image
# transformation with the FIT scale mode) to the corresponding locations on the same image with the letterbox
# removed (the input image to the graph before image transformation).
node {
  calculator: "DetectionLetterboxRemovalCalculator"
  input_stream: "DETECTIONS:filtered_detections"
  input_stream: "LETTERBOX_PADDING:letterbox_padding"
  output_stream: "DETECTIONS:detections"
}
