name: Copilot Setup Steps

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-24.04

    steps:
      - name: Update package lists
        run: sudo apt update

      - name: Install system dependencies for MediaPipe CPU-only build
        run: |
          sudo apt install -y \
            build-essential \
            clang \
            cmake \
            git \
            python3 \
            python3-dev \
            python3-pip \
            pkg-config \
            zip \
            unzip \
            wget \
            curl \
            libopencv-dev \
            libopencv-contrib-dev

      - name: Install Bazel 6.5.0
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-installer-linux-x86_64.sh
          chmod +x bazel-6.5.0-installer-linux-x86_64.sh
          sudo ./bazel-6.5.0-installer-linux-x86_64.sh

      - name: Verify Bazel installation
        run: bazel version
