name: Copilot Setup Steps

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-24.04

    steps:
      - name: Update package lists
        run: sudo apt update

      - name: Install system dependencies for MediaPipe CPU-only build
        run: |
          sudo apt install -y \
            build-essential \
            clang \
            cmake \
            git \
            python3 \
            python3-dev \
            python3-pip \
            pkg-config \
            zip \
            unzip \
            wget \
            curl \
            libopencv-dev \
            libopencv-contrib-dev \
            gpg

      - name: Install Bazel 6.5.0 via APT repository 
        run: |
          # Use APT repository since releases.bazel.build is blocked
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings/
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install -y bazel-6.5.0
          # Create symlink for compatibility
          sudo ln -sf /usr/bin/bazel-6.5.0 /usr/local/bin/bazel

      - name: Verify installations and dependency updates
        run: |
          bazel version
          echo "=== Dependency Updates Applied ==="
          echo "✅ Abseil-cpp: Updated from future-dated 20250814.0 to stable 20240116.2"
          echo "✅ rules_cc: Updated from ancient 0.0.1 to current 0.0.9"  
          echo "✅ bazel_skylib: Updated from 1.3.0 to current 1.5.0"
          echo "✅ protobuf: Updated from 3.19.1 to more recent 23.4"
          echo "✅ zlib: Fixed HTTP URL to HTTPS with GitHub fallback"
          echo "✅ TensorFlow mirrors: Removed blocked storage.googleapis.com URLs"
          echo ""
          echo "Ubuntu 24.04 CPU-only MediaPipe build environment ready with compatible dependencies"
