name: Copilot Setup Steps

permissions:
  contents: read

# an `on` section must be included, so we include only `workflow_dispatch` to allow triggering only by copilot sessions give or take manually dispatching
on:
  workflow_dispatch:

jobs:
  copilot-setup-steps:
    runs-on: self-hosted
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install all system dependencies for the mediapipe build
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc g++ \
            ca-certificates \
            curl \
            ffmpeg \
            git \
            wget \
            unzip \
            nodejs \
            npm \
            python3-dev \
            python3-opencv \
            python3-pip \
            libopencv-core-dev \
            libopencv-highgui-dev \
            libopencv-imgproc-dev \
            libopencv-video-dev \
            libopencv-calib3d-dev \
            libopencv-features2d-dev \
            software-properties-common \
            tar \
            openjdk-21-jdk \
            protobuf-compiler \
            libprotobuf-dev \
            mesa-common-dev \
            libegl1-mesa-dev \
            libgles2-mesa-dev \
            mesa-utils \
            libopenexr-dev \
            libimath-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            libswresample-dev \
            libdc1394-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            pkg-config \
            cmake \
            clang \
            clang-format \
            python3-venv

      - name: Install Bazel
        run: |
          BAZEL_VERSION=6.5.0
          wget --no-check-certificate -O bazel-installer.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
          chmod +x bazel-installer.sh
          sudo ./bazel-installer.sh
          rm -f bazel-installer.sh

      - name: Set up and enter a Python virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
